# Default .credo.exs generated by ex_harness.
# Adjust as needed; this file is not regenerated on subsequent runs.
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "test/"],
        excluded: []
      },
      plugins: [{AshCredo, []}, {ExSlop, []}],
      requires: [],
      strict: true,
      parse_timeout: 5000,
      color: true,
      checks: %{
        enabled: [
          # ex_dna — AI code-duplication detector. Ash `relationships` blocks
          # are declarative config (the same belongs_to shape recurs across
          # tenant-scoped resources by design, like Ecto `schema` bodies) —
          # not copy-pasted logic — so their bodies are skipped.
          {ExDNA.Credo, [excluded_macros: [:relationships]]},
          # ash_credo — Ash framework code-quality checks
          {AshCredo.Check.Warning.AuthorizeFalse, []},
          {AshCredo.Check.Warning.AuthorizerWithoutPolicies, []},
          {AshCredo.Check.Warning.EmptyDomain, []},
          {AshCredo.Check.Warning.MissingDomain, []},
          {AshCredo.Check.Warning.OverlyPermissivePolicy, []},
          {AshCredo.Check.Warning.SensitiveAttributeExposed, []},
          {AshCredo.Check.Warning.SensitiveFieldInAccept, []},
          {AshCredo.Check.Warning.UnknownAction, []},
          {AshCredo.Check.Warning.WildcardAcceptOnAction, []},
          {AshCredo.Check.Refactor.DirectiveInFunctionBody, []},
          {AshCredo.Check.Refactor.LargeResource, []},
          {AshCredo.Check.Refactor.RaisingCall, []},
          {AshCredo.Check.Refactor.UseCodeInterface, []},
          {AshCredo.Check.Design.MissingCodeInterface,
           [
             files: %{
               excluded: ["lib/jido_claw/accounts/user.ex", "lib/jido_claw/accounts/token.ex"]
             },
             # Internal `Ash.Reactor` create-step undo actions (`public?(false)`):
             # invoked only via the saga undo path (`Changeset.for_destroy/3`),
             # never through a code interface by design. See
             # `JidoClaw.Orchestration.ReactorMiddleware` /
             # `JidoClaw.Orchestration.Reactors.ProjectRegistration`.
             # `WorkflowRun.set_status` is the projection-owned status write
             # (`public?(false)`), invoked only by
             # `WorkflowEvent.Changes.Allocate` via `Changeset.for_update/3` —
             # a code interface would invite bypassing the event log.
             excluded_actions: [
               "JidoClaw.Projects.Project.reactor_undo",
               "JidoClaw.Workspaces.Workspace.reactor_undo",
               "JidoClaw.Orchestration.WorkflowRun.set_status"
             ]
           ]},
          {AshCredo.Check.Design.MissingIdentity, []},
          # workflow_run.ex: both update actions (`set_status`,
          # `set_checkpoint`) are internal projection/runner writes
          # (`public?(false)`) — none should be the primary update.
          # composer_artifact.ex: same shape — both updates (`set_active`,
          # `tombstone_active`) are internal `public?(false)` state
          # transitions; a generic primary update would silently flip state.
          {AshCredo.Check.Design.MissingPrimaryAction,
           [
             files: %{
               excluded: [
                 "lib/jido_claw/accounts/token.ex",
                 "lib/jido_claw/orchestration/workflow_run.ex",
                 "lib/jido_claw/orchestration/composer_artifact.ex"
               ]
             }
           ]},
          {AshCredo.Check.Design.MissingTimestamps,
           [
             files: %{
               excluded: [
                 "lib/jido_claw/audit/resources/event.ex",
                 "lib/jido_claw/trace/resources/trace_event.ex"
               ]
             }
           ]},
          {AshCredo.Check.Readability.ActionMissingDescription, []},
          {AshCredo.Check.Readability.BelongsToMissingAllowNil, []},
          # ex_slop — AI code-slop checks (added by ex_harness)
          {ExSlop.Check.Readability.BoilerplateDocParams, []},
          {ExSlop.Check.Readability.DocFalseOnPublicFunction, []},
          {ExSlop.Check.Readability.NarratorComment, []},
          {ExSlop.Check.Readability.NarratorDoc, []},
          {ExSlop.Check.Readability.ObviousComment, []},
          {ExSlop.Check.Readability.StepComment, []},
          {ExSlop.Check.Readability.UnaliasedModuleUse, []},
          {ExSlop.Check.Refactor.CaseTrueFalse, []},
          {ExSlop.Check.Refactor.ExplicitSumReduce, []},
          {ExSlop.Check.Refactor.FilterNil, []},
          {ExSlop.Check.Refactor.FlatMapFilter, []},
          {ExSlop.Check.Refactor.GraphemesLength, []},
          {ExSlop.Check.Refactor.IdentityMap, []},
          {ExSlop.Check.Refactor.IdentityPassthrough, []},
          {ExSlop.Check.Refactor.LengthComparison, []},
          {ExSlop.Check.Refactor.LengthInGuard, []},
          {ExSlop.Check.Refactor.ListFold, []},
          {ExSlop.Check.Refactor.ListLast, []},
          {ExSlop.Check.Refactor.ManualStringReverse, []},
          {ExSlop.Check.Refactor.MapIntoLiteral, []},
          {ExSlop.Check.Refactor.PreferEnumSlice, []},
          {ExSlop.Check.Refactor.ReduceAsMap, []},
          {ExSlop.Check.Refactor.ReduceMapPut, []},
          {ExSlop.Check.Refactor.RedundantBooleanIf, []},
          {ExSlop.Check.Refactor.RedundantEnumJoinSeparator, []},
          {ExSlop.Check.Refactor.RejectNil, []},
          {ExSlop.Check.Refactor.SortForTopK, []},
          {ExSlop.Check.Refactor.SortThenAt, []},
          {ExSlop.Check.Refactor.SortThenReverse, []},
          {ExSlop.Check.Refactor.StringConcatInReduce, []},
          {ExSlop.Check.Refactor.TryRescueWithSafeAlternative, []},
          {ExSlop.Check.Refactor.UseMapJoin, []},
          {ExSlop.Check.Refactor.WithIdentityDo, []},
          {ExSlop.Check.Refactor.WithIdentityElse, []},
          {ExSlop.Check.Warning.BlanketRescue, []},
          {ExSlop.Check.Warning.DualKeyAccess, []},
          {ExSlop.Check.Warning.GenserverAsKvStore, []},
          {ExSlop.Check.Warning.PathExpandPriv, []},
          {ExSlop.Check.Warning.QueryInEnumMap, []},
          {ExSlop.Check.Warning.RepoAllThenFilter, []},
          {ExSlop.Check.Warning.RescueWithoutReraise, []},
          {Credo.Check.Consistency.ExceptionNames, []},
          {Credo.Check.Consistency.LineEndings, []},
          {Credo.Check.Consistency.ParameterPatternMatching, []},
          {Credo.Check.Consistency.SpaceAroundOperators, []},
          {Credo.Check.Consistency.SpaceInParentheses, []},
          {Credo.Check.Consistency.TabsOrSpaces, []},
          {Credo.Check.Design.AliasUsage, [if_nested_deeper_than: 2]},
          # disabled as ExDNA handles this better
          {Credo.Check.Design.DuplicatedCode, false},
          {Credo.Check.Design.SkipTestWithoutComment, []},
          {Credo.Check.Design.TagFIXME, []},
          {Credo.Check.Design.TagTODO, [exit_status: 2]},
          {Credo.Check.Readability.AliasOrder, []},
          {Credo.Check.Readability.BlockPipe, [exclude: [:case, :cond, :if, :with]]},
          {Credo.Check.Readability.FunctionNames, []},
          {Credo.Check.Readability.ImplTrue, []},
          {Credo.Check.Readability.LargeNumbers, []},
          {Credo.Check.Readability.MaxLineLength, [max_length: 120]},
          {Credo.Check.Readability.ModuleAttributeNames, []},
          {Credo.Check.Readability.ModuleDoc, []},
          {Credo.Check.Readability.ModuleNames, []},
          {Credo.Check.Readability.NestedFunctionCalls, [min_pipeline_length: 99]},
          {Credo.Check.Readability.OneArityFunctionInPipe, []},
          {Credo.Check.Readability.OnePipePerLine, []},
          {Credo.Check.Readability.ParenthesesInCondition, []},
          {Credo.Check.Readability.ParenthesesOnZeroArityDefs, []},
          {Credo.Check.Readability.PipeIntoAnonymousFunctions, []},
          {Credo.Check.Readability.PredicateFunctionNames, []},
          {Credo.Check.Readability.PreferImplicitTry, []},
          {Credo.Check.Readability.RedundantBlankLines, []},
          {Credo.Check.Readability.Semicolons, []},
          {Credo.Check.Readability.SeparateAliasRequire, []},
          {Credo.Check.Readability.SingleFunctionToBlockPipe, []},
          {Credo.Check.Readability.SinglePipe, [allow_blocks: true]},
          {Credo.Check.Readability.SpaceAfterCommas, []},
          {Credo.Check.Readability.Specs, []},
          {Credo.Check.Readability.StringSigils, []},
          {Credo.Check.Readability.TrailingBlankLine, []},
          {Credo.Check.Readability.TrailingWhiteSpace, []},
          {Credo.Check.Readability.UnnecessaryAliasExpansion, []},
          {Credo.Check.Readability.VariableNames, []},
          {Credo.Check.Readability.WithCustomTaggedTuple, []},
          {Credo.Check.Readability.WithSingleClause, []},
          {Credo.Check.Refactor.ABCSize, [max_size: 999]},
          {Credo.Check.Refactor.AppendSingleItem, []},
          {Credo.Check.Refactor.Apply, []},
          {Credo.Check.Refactor.CaseTrivialMatches, []},
          {Credo.Check.Refactor.CondStatements, []},
          {Credo.Check.Refactor.CyclomaticComplexity, [max_complexity: 11]},
          {Credo.Check.Refactor.DoubleBooleanNegation, []},
          {Credo.Check.Refactor.FilterCount, []},
          {Credo.Check.Refactor.FilterFilter, []},
          {Credo.Check.Refactor.FilterReject, []},
          {Credo.Check.Refactor.FunctionArity, []},
          {Credo.Check.Refactor.LongQuoteBlocks, []},
          {Credo.Check.Refactor.MapJoin, []},
          {Credo.Check.Refactor.MapMap, []},
          {Credo.Check.Refactor.MatchInCondition, []},
          {Credo.Check.Refactor.ModuleDependencies, [max_deps: 999]},
          {Credo.Check.Refactor.NegatedConditionsInUnless, []},
          {Credo.Check.Refactor.NegatedConditionsWithElse, []},
          {Credo.Check.Refactor.Nesting, [max_nesting: 3]},
          {Credo.Check.Refactor.PassAsyncInTestCases, []},
          {Credo.Check.Refactor.PerceivedComplexity, [max_complexity: 11]},
          {Credo.Check.Refactor.RedundantWithClauseResult, []},
          {Credo.Check.Refactor.RejectFilter, []},
          {Credo.Check.Refactor.RejectReject, []},
          {Credo.Check.Refactor.UnlessWithElse, []},
          {Credo.Check.Refactor.VariableRebinding, []},
          {Credo.Check.Refactor.WithClauses, []},
          {Credo.Check.Warning.ApplicationConfigInModuleAttribute, []},
          {Credo.Check.Warning.BoolOperationOnSameValues, []},
          {Credo.Check.Warning.Dbg, []},
          {Credo.Check.Warning.ExpensiveEmptyEnumCheck, []},
          {Credo.Check.Warning.IExPry, []},
          {Credo.Check.Warning.IoInspect, []},
          {Credo.Check.Warning.LeakyEnvironment, []},
          {Credo.Check.Warning.MapGetUnsafePass, []},
          {Credo.Check.Warning.MissedMetadataKeyInLoggerConfig, []},
          # Mix tasks/compilers legitimately branch on Mix.env(); the check
          # targets application code, where Mix is unavailable in releases.
          {Credo.Check.Warning.MixEnv, [files: %{excluded: ["lib/mix/"]}]},
          {Credo.Check.Warning.OperationOnSameValues, []},
          {Credo.Check.Warning.OperationWithConstantResult, []},
          {Credo.Check.Warning.RaiseInsideRescue, []},
          {Credo.Check.Warning.SpecWithStruct, []},
          {Credo.Check.Warning.StructFieldAmount, []},
          {Credo.Check.Warning.UnsafeExec, []},
          {Credo.Check.Warning.UnsafeToAtom, []},
          {Credo.Check.Warning.UnusedEnumOperation, []},
          {Credo.Check.Warning.UnusedFileOperation, []},
          {Credo.Check.Warning.UnusedKeywordOperation, []},
          {Credo.Check.Warning.UnusedListOperation, []},
          {Credo.Check.Warning.UnusedMapOperation, []},
          {Credo.Check.Warning.UnusedPathOperation, []},
          {Credo.Check.Warning.UnusedRegexOperation, []},
          {Credo.Check.Warning.UnusedStringOperation, []},
          {Credo.Check.Warning.UnusedTupleOperation, []},
          {Credo.Check.Warning.WrongTestFileExtension, []},
          {Credo.Check.Warning.WrongTestFilename, []}
        ],
        disabled: [
          {Credo.Check.Consistency.MultiAliasImportRequireUse, []},
          {Credo.Check.Consistency.UnusedVariableNames, []},
          {Credo.Check.Readability.AliasAs, []},
          {Credo.Check.Readability.MultiAlias, []},
          {Credo.Check.Readability.StrictModuleLayout, []},
          {Credo.Check.Refactor.PipeChainStart, []}
        ]
      }
    }
  ]
}
