defmodule JidoClaw.Agent.Defaults do
  @moduledoc """
  `use JidoClaw.Agent.Defaults` is a thin wrapper around
  `use Jido.AI.Agent` that injects the `Recorder` plugin and (opt-in) the
  context-compaction `on_before_cmd/2` override.

  Used by the main `JidoClaw.Agent` and the seven specialized agent
  workers (Coder, Reviewer, Researcher, Refactorer, Verifier,
  TestRunner, DocsWriter). The Recorder plugin bridges the agent's
  `ai.*` mailbox signals onto `JidoClaw.SignalBus` so the
  `Conversations.Recorder` GenServer can persist tool activity into
  Postgres.

  All `Jido.AI.Agent` options pass through unchanged. Per-site
  `:plugins` lists are appended to the base plugins, so existing
  plugin configurations are preserved.

  ## Compaction (`:compaction` opt)

  The macro pops a `:compaction` keyword from `__using__/1` opts, builds
  a `JidoClaw.Reasoning.Compactor.Config` at compile time, and injects:

    * `__compaction_config__/0` — returns the validated `%Config{}`.
    * An `on_before_cmd/2` override matched on `{:ai_react_start, _}`
      that runs `JidoClaw.Reasoning.Compactor.maybe_compact/3`, then
      delegates to `super/2`.

  When `compaction: [mode: :off]` (also the no-op fallback when no
  `:compaction` opt is passed) the override still fires but
  `maybe_compact/3` short-circuits at the pattern-match level
  (`%Config{mode: :off}` clause) — no I/O, no storage reads.

  Compaction is best-effort. If `maybe_compact/3` returns `{:error, _}`,
  the override falls through with the original action so the agent
  always makes forward progress.

  ## Why a macro

  Without this layer, every `use Jido.AI.Agent` site would need an
  explicit `plugins: [JidoClaw.AgentServerPlugin.Recorder, ...]`
  entry. Adding a new agent worker without that line silently drops
  its tool activity from the persistence layer. The macro makes the
  Recorder plugin opt-out by editing one place — and the §G
  acceptance test ("Recorder plugin coverage CI gate") asserts every
  agent declaration site routes through this wrapper.
  """

  alias JidoClaw.Reasoning.Compactor.Config

  defmacro __using__(opts) do
    {compaction_opts, opts} = Keyword.pop(opts, :compaction, [])

    compaction_config = build_compaction_config!(compaction_opts)
    escaped_config = Macro.escape(compaction_config)

    base_plugins = [JidoClaw.AgentServerPlugin.Recorder]
    opts = Keyword.update(opts, :plugins, base_plugins, &(base_plugins ++ &1))

    quote do
      use Jido.AI.Agent, unquote(opts)

      @doc """
      Returns the compaction configuration this agent module was compiled
      with. Internal — used by the `on_before_cmd/2` override generated by
      `JidoClaw.Agent.Defaults`.
      """
      def __compaction_config__, do: unquote(escaped_config)

      # credo:disable-for-next-line Credo.Check.Design.AliasUsage
      @compactor JidoClaw.Reasoning.Compactor

      def on_before_cmd(agent, {:ai_react_start, _params} = action) do
        next_action =
          case @compactor.maybe_compact(agent, action, __compaction_config__()) do
            {:ok, new_action} -> new_action
            {:error, _reason} -> action
          end

        super(agent, next_action)
      end

      def on_before_cmd(agent, action), do: super(agent, action)
    end
  end

  @doc """
  Build a `JidoClaw.Reasoning.Compactor.Config` from the `:compaction` opt
  passed to `use JidoClaw.Agent.Defaults`. Called at macro expansion time
  in the consuming module; not part of the runtime public API. Raises on
  invalid configuration so misconfigured agents fail at compile time.
  """
  def build_compaction_config!(compaction_opts) do
    normalized =
      cond do
        is_list(compaction_opts) and compaction_opts == [] ->
          [mode: :off]

        is_list(compaction_opts) ->
          compaction_opts

        is_map(compaction_opts) and map_size(compaction_opts) == 0 ->
          [mode: :off]

        is_map(compaction_opts) ->
          Map.to_list(compaction_opts)

        true ->
          [mode: :off]
      end

    Config.new!(normalized)
  end
end
