defmodule JidoClaw.Web.GraphQL.Schema do
  @moduledoc """
  The read-only Absinthe schema behind `/gql` (argus P1): AshGraphql-derived
  queries over `JidoClaw.Projects` and `JidoClaw.Orchestration` — nothing
  else. No mutation or subscription root exists; the resources' `graphql`
  blocks are positive `show_fields` allowlists.

  The committed golden `ui/schema.graphql` pins this schema's SDL —
  regenerated by `mix jidoclaw.graphql.schema` and drift-guarded by
  `mix jidoclaw.graphql.schema.check` in the `precommit` alias (the single
  writer; AshGraphql's own `generate_sdl_file` codegen is deliberately not
  used so the golden has exactly one authority).
  """

  use Absinthe.Schema
  use AshGraphql, domains: [JidoClaw.Projects, JidoClaw.Orchestration]

  # Empty by design — AshGraphql injects the domain queries into this root
  # during schema compilation (the block must exist for the root type to be
  # defined; no placeholder fields).
  query do
  end
end
