defmodule JidoClaw.VFS.Sandbox do
  @moduledoc """
  Creation + validation of the throwaway sketch sandbox root
  `<project>/.prototypes/<uuid>/` (AR-8b).

  Single-sources the path-safety the sketch path depends on, so neither the
  front door (which *creates* a sandbox dir), nor `Skills.Steps.AgentRunner`
  (which *re-validates* one before running a worker), nor the file tools (which
  derive their `Resolver` opts via `resolver_opts/1`) re-implement it. It
  defeats the two concrete escapes review named:

    * a crafted `<base>/.prototypes/../real-dir` (collapsed lexically by
      `Path.expand/1`, then rejected on the basename shape check), and
    * a planted `<base>/.prototypes` **symlink** (which `File.mkdir_p/1` would
      happily follow into another tree) — rejected by an `lstat` on the parent
      *and* a realpath-basename re-check, so a `.prototypes -> /elsewhere/.prototypes`
      link whose target basename is *also* `.prototypes` still fails.

  The `<uuid>` child is generated by us (`Ash.UUID.generate/0`), never
  attacker-influenced, so the child basename always matches `@uuid`.
  """

  alias JidoClaw.VFS.Resolver

  @uuid ~r/\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/

  @doc """
  Create a fresh per-prototype sandbox dir under `base/.prototypes/`, symlink-safe
  and validated. Returns `{:ok, %{dir: dir, id: id}}` or `{:error, reason}`.

  `base` must **already exist** (a missing base is `{:error, :base_not_a_directory}`,
  not a fabricated phantom project tree). A planted `.prototypes` symlink is
  `{:error, :symlinked_prototypes}` with the link left untouched. `nil`/`""`
  surface as `{:error, :missing_project_dir}`.
  """
  @spec create_prototype_dir(term()) ::
          {:ok, %{dir: String.t(), id: String.t()}} | {:error, term()}
  def create_prototype_dir(base) when is_binary(base) and base != "" do
    expanded_base = Path.expand(base)
    root = Path.join(expanded_base, ".prototypes")

    with :ok <- ensure_existing_dir(expanded_base),
         :ok <- reject_symlink(root),
         :ok <- File.mkdir_p(root),
         id = Ash.UUID.generate(),
         dir = Path.join(root, id),
         :ok <- File.mkdir_p(dir),
         :ok <- validate_root(dir) do
      {:ok, %{dir: dir, id: id}}
    end
  end

  def create_prototype_dir(_), do: {:error, :missing_project_dir}

  @doc """
  True when `name` (a `.prototypes/` child basename or path) is shaped like a
  prototype dir — a bare UUID. Single-sources the `@uuid` regex so the retention
  sweeper (`JidoClaw.VFS.PrototypeRetentionSweeper`) doesn't re-declare it.
  """
  @spec uuid_child?(term()) :: boolean()
  def uuid_child?(name) when is_binary(name), do: Regex.match?(@uuid, Path.basename(name))
  def uuid_child?(_name), do: false

  @doc """
  Validate an existing path IS a legit `.prototypes/<uuid>/` root — lexical
  shape, `lstat` symlink rejection on the `.prototypes` parent, a real-directory
  check on the child, and a realpath under-parent check.

  Independent layers, so a write can only ever land under the real, ignored
  `.prototypes/<uuid>/`. Returns `:ok` or `{:error, reason}`.
  """
  @spec validate_root(String.t()) :: :ok | {:error, term()}
  def validate_root(dir) when is_binary(dir) do
    expanded = Path.expand(dir)
    parent = Path.dirname(expanded)

    with :ok <- ensure(Path.basename(parent) == ".prototypes", :not_under_prototypes),
         :ok <- ensure(uuid_child?(expanded), :child_not_uuid),
         # lstat the parent ITSELF: a `<base>/.prototypes -> /elsewhere/.prototypes`
         # symlink would otherwise pass the realpath-basename check below (the
         # target's basename is also `.prototypes`).
         :ok <- reject_symlink(parent),
         :ok <- ensure_real_directory(expanded),
         {:ok, real_dir} <- Resolver.realpath(expanded),
         {:ok, real_parent} <- Resolver.realpath(parent),
         :ok <- ensure(Path.basename(real_parent) == ".prototypes", :symlinked_prototypes) do
      ensure(under?(real_dir, real_parent), :escapes_prototypes)
    end
  end

  def validate_root(_), do: {:error, :invalid_sandbox_root}

  @doc """
  Derive the **real project base** (`<real>`) from a sketch sandbox `project_dir`
  (`<real>/.prototypes/<uuid>/`) — the root the read-only real-tree tools
  (AR-8b-2 F3) jail their reads to.

  Single-sources the derivation: runs `validate_root/1` (rejecting any path that
  is not a real `.prototypes/<uuid>/` root, incl. lexical/symlink escapes), then
  returns `{:ok, Path.dirname(Path.dirname(expanded))}`. `validate_root/1`
  guarantees `.prototypes` is not a symlink (lstat on the parent), so the lexical
  grandparent is the real base — deterministically (review §5). Fails CLOSED:
  any non-prototype / invalid root surfaces `{:error, reason}`.
  """
  @spec real_root(term()) :: {:ok, String.t()} | {:error, term()}
  def real_root(project_dir) when is_binary(project_dir) and project_dir != "" do
    expanded = Path.expand(project_dir)

    with :ok <- validate_root(expanded) do
      {:ok, Path.dirname(Path.dirname(expanded))}
    end
  end

  def real_root(_), do: {:error, :invalid_sandbox_root}

  @doc """
  Derive `Resolver` opts (`workspace_id`/`project_dir`/`local_only`) from a
  tool's `tool_context`.

  Fails CLOSED for a `sandbox: :prototype` context: a sketch tool call MUST
  carry a `project_dir` that `validate_root/1` accepts — never the `File.cwd!()`
  fallback (review P2). Non-sandbox contexts keep the existing
  `project_dir || File.cwd!()` default.
  """
  @spec resolver_opts(map() | nil) :: {:ok, keyword()} | {:error, term()}
  def resolver_opts(tool_context) when is_map(tool_context) do
    workspace_id = Map.get(tool_context, :workspace_id)

    case Map.get(tool_context, :sandbox) do
      :prototype ->
        sandbox_resolver_opts(workspace_id, Map.get(tool_context, :project_dir))

      _ ->
        {:ok,
         [
           workspace_id: workspace_id,
           project_dir: Map.get(tool_context, :project_dir) || File.cwd!(),
           local_only: false
         ]}
    end
  end

  def resolver_opts(_), do: resolver_opts(%{})

  # `File.stat` FOLLOWS symlinks — a legitimately symlinked project root is fine.
  # The point of this check is to reject a *missing* base, so `File.mkdir_p/1`
  # can't fabricate a phantom project tree out of a wrong path.
  defp ensure_existing_dir(path) do
    case File.stat(path) do
      {:ok, %File.Stat{type: :directory}} -> :ok
      _ -> {:error, :base_not_a_directory}
    end
  end

  # `File.lstat` does NOT follow symlinks. A symlink at this path is rejected;
  # a non-symlink (including `:enoent` for a not-yet-created path) is `:ok`.
  defp reject_symlink(path) do
    case File.lstat(path) do
      {:ok, %File.Stat{type: :symlink}} -> {:error, :symlinked_prototypes}
      _ -> :ok
    end
  end

  # lstat does NOT follow: a symlink → :symlinked_prototypes (preserves the prior
  # reason for a symlinked child); a regular file or a missing path →
  # :not_a_directory (the review P3 fix). An lstat-dir check subsumes symlink
  # rejection (a symlink's type is :symlink, never :directory).
  defp ensure_real_directory(path) do
    case File.lstat(path) do
      {:ok, %File.Stat{type: :directory}} -> :ok
      {:ok, %File.Stat{type: :symlink}} -> {:error, :symlinked_prototypes}
      _ -> {:error, :not_a_directory}
    end
  end

  defp sandbox_resolver_opts(workspace_id, project_dir)
       when is_binary(project_dir) and project_dir != "" do
    case validate_root(project_dir) do
      :ok ->
        {:ok, [workspace_id: workspace_id, project_dir: project_dir, local_only: true]}

      # inspect/1, not raw interpolation: validate_root/1 is specced term(), so a
      # tuple reason (e.g. realpath's) would raise under `#{...}`.
      {:error, reason} ->
        {:error,
         "sketch sandbox scope invalid (#{inspect(reason)}): project_dir is not a validated .prototypes/<uuid>/ root"}
    end
  end

  defp sandbox_resolver_opts(_workspace_id, _project_dir),
    do:
      {:error,
       "sketch sandbox scope missing: a sandboxed tool call requires a validated .prototypes/<uuid>/ project_dir"}

  defp ensure(true, _reason), do: :ok
  defp ensure(false, reason), do: {:error, reason}

  # Mirror of Resolver.under_path?/2 (private there): `child` is at or below
  # `parent` (never an escaping `../`).
  defp under?(child, parent) do
    relative = Path.relative_to(child, parent)

    relative == "." or
      (relative != child and relative != ".." and not String.starts_with?(relative, "../"))
  end
end
