defmodule JidoClaw.Repo.Migrations.Ws1Ws2StepTenancyRunClaims do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_steps) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "workflow_steps_tenant_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false
    end

    alter table(:workflow_runs) do
      add :claimed_by, :text
      add :claim_expires_at, :utc_datetime_usec
      add :claim_token, :uuid
    end

    create index(:workflow_runs, [:claimed_by])

    create index(:workflow_runs, [:status, :claim_expires_at])
  end

  def down do
    drop_if_exists index(:workflow_runs, [:status, :claim_expires_at])

    drop_if_exists index(:workflow_runs, [:claimed_by])

    alter table(:workflow_runs) do
      remove :claim_token
      remove :claim_expires_at
      remove :claimed_by
    end

    drop constraint(:workflow_steps, "workflow_steps_tenant_id_fkey")

    alter table(:workflow_steps) do
      remove :tenant_id
    end
  end
end
