defmodule JidoClaw.Repo.Migrations.AddIssueAnalysisIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists(
      unique_index(:github_issue_analyses, [:repo_full_name, :issue_number],
        name: "github_issue_analyses_unique_issue_per_repo_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:github_issue_analyses, [:repo_full_name, :issue_number],
        name: "github_issue_analyses_unique_issue_per_repo_index"
      )
    )
  end
end
