defmodule JidoClaw.Repo.Migrations.AddWorkflowStepDependsOn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_steps) do
      add :depends_on, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:workflow_steps) do
      remove :depends_on
    end
  end
end
