defmodule JidoClaw.Repo.Migrations.CronDefinitionFence do
  @moduledoc """
  Adds `cron_jobs.definition_token` (the worker definition-generation fence).

  Originally autogenerated with `mix ash_postgres.generate_migrations`, then
  hand-edited into the safe 3-step shape: a single
  `ADD COLUMN ... NOT NULL DEFAULT gen_random_uuid()` evaluates a VOLATILE
  default, forcing a full table rewrite under one long lock. Adding the
  column nullable, backfilling explicitly, and only then attaching
  NOT NULL + the default keeps each step short. The snapshot is untouched —
  it describes the end state, which is identical.
  """

  use Ecto.Migration

  def up do
    alter table(:cron_jobs) do
      add :definition_token, :uuid, null: true
    end

    execute "UPDATE cron_jobs SET definition_token = gen_random_uuid() WHERE definition_token IS NULL"

    alter table(:cron_jobs) do
      modify :definition_token, :uuid, null: false, default: fragment("gen_random_uuid()")
    end
  end

  def down do
    alter table(:cron_jobs) do
      remove :definition_token
    end
  end
end
