defmodule JidoClaw.Repo.Migrations.AddReplayFingerprintColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_runs) do
      add :definition_hash, :text
      add :encrypted_replay_inputs, :binary
    end
  end

  def down do
    alter table(:workflow_runs) do
      remove :encrypted_replay_inputs
      remove :definition_hash
    end
  end
end
