defmodule JidoClaw.Repo.Migrations.AddSessionAgentToReasoningOutcomes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reasoning_outcomes) do
      add(:agent_id, :text)
      add(:forge_session_key, :text)
    end

    create(index(:reasoning_outcomes, [:agent_id, :started_at]))

    create(index(:reasoning_outcomes, [:forge_session_key]))
  end

  def down do
    drop_if_exists(index(:reasoning_outcomes, [:forge_session_key]))

    drop_if_exists(index(:reasoning_outcomes, [:agent_id, :started_at]))

    alter table(:reasoning_outcomes) do
      remove(:forge_session_key)
      remove(:agent_id)
    end
  end
end
