defmodule JidoClaw.Repo.Migrations.AddComposerArtifact do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:composer_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ref, :text, null: false
      add :name, :text, null: false
      add :producer, :text, null: false
      add :state, :text, null: false, default: "pending"
      add :child_run_id, :uuid, null: false
      add :wave_index, :bigint, null: false
      add :parent_run_id, :uuid, null: false
      add :tenant_id, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_value, :binary
    end

    create index(:composer_artifacts, [:tenant_id, :parent_run_id, :name, :producer],
             name: "composer_artifacts_active_ref_index",
             unique: true,
             where: "state = 'active'"
           )

    create index(:composer_artifacts, [:tenant_id, :parent_run_id, :name])

    create unique_index(:composer_artifacts, [:tenant_id, :ref],
             name: "composer_artifacts_unique_ref_index"
           )

    alter table(:request_correlations) do
      add :sanitize_sensitive_context, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:request_correlations) do
      remove :sanitize_sensitive_context
    end

    drop_if_exists unique_index(:composer_artifacts, [:tenant_id, :ref],
                     name: "composer_artifacts_unique_ref_index"
                   )

    drop_if_exists index(:composer_artifacts, [:tenant_id, :parent_run_id, :name])

    drop_if_exists index(:composer_artifacts, [:tenant_id, :parent_run_id, :name, :producer],
                     name: "composer_artifacts_active_ref_index"
                   )

    drop table(:composer_artifacts)
  end
end
