defmodule JidoClaw.Repo.Migrations.AddToolOutputStore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tool_outputs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ref, :text, null: false
      add :tenant_id, :text, null: false

      add :session_id,
          references(:conversation_sessions,
            column: :id,
            name: "tool_outputs_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :command_fingerprint, :text
      add :tool, :text, null: false
      add :command, :text
      add :content, :text, null: false
      add :byte_size, :bigint
      add :truncated, :boolean, null: false, default: false
      add :exit_code, :bigint
      add :summary, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:tool_outputs, [:tenant_id, :inserted_at])

    create index(:tool_outputs, [:tenant_id, :session_id, :command_fingerprint])

    create unique_index(:tool_outputs, [:tenant_id, :ref], name: "tool_outputs_unique_ref_index")
  end

  def down do
    drop constraint(:tool_outputs, "tool_outputs_session_id_fkey")

    drop_if_exists unique_index(:tool_outputs, [:tenant_id, :ref],
                     name: "tool_outputs_unique_ref_index"
                   )

    drop_if_exists index(:tool_outputs, [:tenant_id, :session_id, :command_fingerprint])

    drop_if_exists index(:tool_outputs, [:tenant_id, :inserted_at])

    drop table(:tool_outputs)
  end
end
