defmodule JidoClaw.Repo.Migrations.AddSessionWorkspaceLastActiveIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:conversation_sessions, [:tenant_id, :workspace_id, :last_active_at])
  end

  def down do
    drop_if_exists index(:conversation_sessions, [:tenant_id, :workspace_id, :last_active_at])
  end
end
