defmodule JidoClaw.Repo.Migrations.V061Solutions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # IMMUTABLE wrappers for the generated-column expressions. Postgres
    # requires generation expressions to be IMMUTABLE, but two functions
    # we need are only STABLE:
    #
    #   * `to_tsvector(regconfig, text)` — STABLE because the regconfig
    #     lookup goes through pg_ts_config.
    #   * `array_to_string(anyarray, text)` — STABLE because element-cast
    #     functions can be STABLE for some array types.
    #
    # Both are effectively immutable for our usage (fixed 'english' config,
    # text[] inputs only), so wrapping them in IMMUTABLE SQL functions is
    # the standard, safe workaround.
    #
    # Hand-written via execute/1 because Ecto/AshPostgres migration DSLs
    # have no DDL for CREATE FUNCTION.
    execute("""
    CREATE OR REPLACE FUNCTION solutions_search_vector(
      p_language text,
      p_framework text,
      p_tags text[],
      p_content text
    ) RETURNS tsvector AS $$
      SELECT
        setweight(to_tsvector('english', coalesce(p_language, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(p_framework, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(array_to_string(p_tags, ' '), '')), 'B') ||
        setweight(to_tsvector('english', coalesce(p_content, '')), 'C')
    $$ LANGUAGE SQL IMMUTABLE
    """)

    execute("""
    CREATE OR REPLACE FUNCTION solutions_lexical_text(
      p_language text,
      p_framework text,
      p_tags text[],
      p_content text
    ) RETURNS text AS $$
      SELECT lower(
        coalesce(p_language, '') || ' ' ||
        coalesce(p_framework, '') || ' ' ||
        coalesce(array_to_string(p_tags, ' '), '') || ' ' ||
        coalesce(p_content, '')
      )
    $$ LANGUAGE SQL IMMUTABLE
    """)

    create table(:solutions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:problem_signature, :text, null: false)
      add(:solution_content, :text, null: false)
      add(:language, :text, null: false)
      add(:framework, :text)
      add(:runtime, :text)
      add(:agent_id, :text)
      add(:tags, {:array, :text}, null: false, default: [])
      add(:verification, :map, null: false, default: %{})
      add(:trust_score, :float, null: false, default: 0.0)
      add(:sharing, :text, null: false, default: "local")

      add(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "solutions_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "solutions_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :created_by_user_id,
        references(:users,
          column: :id,
          name: "solutions_created_by_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:tenant_id, :text, null: false)
      add(:embedding, :vector, size: 1024)
      add(:embedding_status, :text, null: false, default: "pending")
      add(:embedding_attempt_count, :bigint, null: false, default: 0)
      add(:embedding_next_attempt_at, :utc_datetime_usec)
      add(:embedding_last_error, :text)
      add(:embedding_model, :text)

      # GENERATED ALWAYS columns — Ecto's `:generated` option emits the
      # PG clause inline. Hand-edited (AshPostgres won't emit `:generated`
      # from a resource attribute), but kept declarative within the
      # `create table` block.
      add(:search_vector, :tsvector,
        generated:
          "ALWAYS AS (solutions_search_vector(language, framework, tags, solution_content)) STORED"
      )

      add(:lexical_text, :text,
        generated:
          "ALWAYS AS (solutions_lexical_text(language, framework, tags, solution_content)) STORED"
      )

      add(:deleted_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:solutions, [:search_vector], using: "gin"))

    # GIN trigram index on lexical_text — required for similarity()
    # ranking and ESCAPE-protected LIKE substring filters in the
    # hybrid retrieval CTE pool.
    execute("""
    CREATE INDEX solutions_lexical_text_trgm_idx
      ON solutions USING gin (lexical_text gin_trgm_ops)
    """)

    # Partial HNSW indexes per embedding_model — pgvector's HNSW only
    # ranks against one opclass per index. The §1.5 ANN CTE filters
    # `embedding_model = $11`, which lets the planner pick the matching
    # partial index for each query.
    execute("""
    CREATE INDEX solutions_embedding_voyage_hnsw_idx
      ON solutions USING hnsw (embedding vector_cosine_ops)
      WHERE embedding_model = 'voyage-4-large'
    """)

    execute("""
    CREATE INDEX solutions_embedding_local_hnsw_idx
      ON solutions USING hnsw (embedding vector_cosine_ops)
      WHERE embedding_model = 'mxbai-embed-large'
    """)

    create(index(:solutions, [:tenant_id, :embedding_status]))

    create(index(:solutions, [:tenant_id, :trust_score]))

    create(index(:solutions, [:tenant_id, :sharing]))

    create(index(:solutions, [:tenant_id, :agent_id]))

    create(index(:solutions, [:tenant_id, :language, :framework]))

    create(index(:solutions, [:tenant_id, :workspace_id]))

    create(index(:solutions, [:tenant_id, :problem_signature]))

    create table(:reputations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:agent_id, :text, null: false)
      add(:score, :float, null: false, default: 0.5)
      add(:solutions_verified, :bigint, null: false, default: 0)
      add(:solutions_failed, :bigint, null: false, default: 0)
      add(:solutions_shared, :bigint, null: false, default: 0)
      add(:last_active, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:reputations, [:tenant_id, :score]))

    create(
      unique_index(:reputations, [:tenant_id, :agent_id],
        name: "reputations_unique_tenant_agent_index"
      )
    )

    create table(:reputation_imports, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:source_sha256, :text, null: false)
      add(:source_path, :text)
      add(:imported_at, :utc_datetime_usec, null: false)
      add(:rows_imported, :bigint, null: false, default: 0)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:reputation_imports, [:tenant_id, :source_sha256],
        name: "reputation_imports_unique_tenant_source_index"
      )
    )

    create table(:embedding_dispatch_window, primary_key: false) do
      add(:model, :text, null: false, primary_key: true)
      add(:window_started_at, :utc_datetime_usec, null: false, primary_key: true)
      add(:request_count, :bigint, null: false, default: 0)
      add(:token_count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:embedding_dispatch_window))

    drop_if_exists(
      unique_index(:reputation_imports, [:tenant_id, :source_sha256],
        name: "reputation_imports_unique_tenant_source_index"
      )
    )

    drop(table(:reputation_imports))

    drop_if_exists(
      unique_index(:reputations, [:tenant_id, :agent_id],
        name: "reputations_unique_tenant_agent_index"
      )
    )

    drop_if_exists(index(:reputations, [:tenant_id, :score]))

    drop(table(:reputations))

    drop(constraint(:solutions, "solutions_workspace_id_fkey"))

    drop(constraint(:solutions, "solutions_session_id_fkey"))

    drop(constraint(:solutions, "solutions_created_by_user_id_fkey"))

    drop_if_exists(index(:solutions, [:tenant_id, :problem_signature]))

    drop_if_exists(index(:solutions, [:tenant_id, :workspace_id]))

    drop_if_exists(index(:solutions, [:tenant_id, :language, :framework]))

    drop_if_exists(index(:solutions, [:tenant_id, :agent_id]))

    drop_if_exists(index(:solutions, [:tenant_id, :sharing]))

    drop_if_exists(index(:solutions, [:tenant_id, :trust_score]))

    drop_if_exists(index(:solutions, [:tenant_id, :embedding_status]))

    execute("DROP INDEX IF EXISTS solutions_embedding_local_hnsw_idx")
    execute("DROP INDEX IF EXISTS solutions_embedding_voyage_hnsw_idx")
    execute("DROP INDEX IF EXISTS solutions_lexical_text_trgm_idx")

    drop_if_exists(index(:solutions, [:search_vector]))

    drop(table(:solutions))

    execute("DROP FUNCTION IF EXISTS solutions_lexical_text(text, text, text[], text)")
    execute("DROP FUNCTION IF EXISTS solutions_search_vector(text, text, text[], text)")
  end
end
