defmodule JidoClaw.Repo.Migrations.Ws3StepIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:workflow_steps, [:tenant_id, :workflow_run_id, :name],
             name: "workflow_steps_unique_step_per_run_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workflow_steps, [:tenant_id, :workflow_run_id, :name],
                     name: "workflow_steps_unique_step_per_run_index"
                   )
  end
end
