defmodule JidoClaw.Repo.Migrations.Ws5Ws9CaseEventsCloak do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_runs) do
      remove :resume_checkpoint
      add :encrypted_resume_checkpoint, :binary
    end

    create table(:agent_case_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "agent_case_events_tenant_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false

      add :seq, :bigint, null: false
      add :type, :text, null: false
      add :data, :map, null: false, default: %{}

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_case_id,
          references(:agent_cases,
            column: :id,
            name: "agent_case_events_agent_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:agent_case_events, [:tenant_id, :agent_case_id, :seq], unique: true)
  end

  def down do
    drop constraint(:agent_case_events, "agent_case_events_tenant_id_fkey")

    drop constraint(:agent_case_events, "agent_case_events_agent_case_id_fkey")

    drop_if_exists index(:agent_case_events, [:tenant_id, :agent_case_id, :seq])

    drop table(:agent_case_events)

    alter table(:workflow_runs) do
      remove :encrypted_resume_checkpoint
      add :resume_checkpoint, :binary
    end
  end
end
