defmodule JidoClaw.Repo.Migrations.AddForgeEventIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(index(:forge_events, [:session_id, :timestamp]))

    create(index(:forge_checkpoints, [:session_id, :created_at]))
  end

  def down do
    drop_if_exists(index(:forge_checkpoints, [:session_id, :created_at]))

    drop_if_exists(index(:forge_events, [:session_id, :timestamp]))
  end
end
