defmodule JidoClaw.Repo.Migrations.AddWorkflowRunIdempotencyKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_runs) do
      add :idempotency_key, :text
    end

    create unique_index(:workflow_runs, [:tenant_id, :idempotency_key],
             name: "workflow_runs_unique_run_idempotency_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workflow_runs, [:tenant_id, :idempotency_key],
                     name: "workflow_runs_unique_run_idempotency_index"
                   )

    alter table(:workflow_runs) do
      remove :idempotency_key
    end
  end
end
