defmodule JidoClaw.Repo.Migrations.CreateReasoningOutcomes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reasoning_outcomes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:strategy, :text, null: false)
      add(:execution_kind, :text, null: false)
      add(:base_strategy, :text)
      add(:pipeline_name, :text)
      add(:pipeline_stage, :text)
      add(:task_type, :text, null: false)
      add(:complexity, :text, null: false)
      add(:domain, :text)
      add(:target, :text)
      add(:prompt_length, :bigint, null: false)
      add(:status, :text, null: false)
      add(:duration_ms, :bigint)
      add(:tokens_in, :bigint)
      add(:tokens_out, :bigint)
      add(:certificate_verdict, :text)
      add(:certificate_confidence, :float)
      add(:workspace_id, :text)
      add(:project_dir, :text)
      add(:metadata, :map, default: %{})
      add(:started_at, :utc_datetime_usec, null: false)
      add(:completed_at, :utc_datetime_usec)
    end

    create(index(:reasoning_outcomes, [:status, :task_type]))

    create(index(:reasoning_outcomes, [:workspace_id, :started_at]))

    create(index(:reasoning_outcomes, [:execution_kind, :task_type]))

    create(index(:reasoning_outcomes, [:strategy, :task_type]))
  end

  def down do
    drop_if_exists(index(:reasoning_outcomes, [:strategy, :task_type]))

    drop_if_exists(index(:reasoning_outcomes, [:execution_kind, :task_type]))

    drop_if_exists(index(:reasoning_outcomes, [:workspace_id, :started_at]))

    drop_if_exists(index(:reasoning_outcomes, [:status, :task_type]))

    drop(table(:reasoning_outcomes))
  end
end
