defmodule JidoClaw.Repo.Migrations.CreateForgeTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forge_sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:phase, :text, null: false, default: "created")
      add(:runner_type, :text)
      add(:runner_config, :map, default: %{})
      add(:spec, :map, default: %{})
      add(:sprite_id, :text)
      add(:execution_count, :bigint, null: false, default: 0)
      add(:last_error, :text)
      add(:metadata, :map, default: %{})
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:last_activity_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:forge_exec_sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:sequence, :bigint, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:command, :text)
      add(:exit_code, :bigint)
      add(:output, :text)
      add(:output_size_bytes, :bigint)
      add(:duration_ms, :bigint)
      add(:metadata, :map, default: %{})
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :session_id,
        references(:forge_sessions,
          column: :id,
          name: "forge_exec_sessions_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:forge_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:event_type, :text, null: false)
      add(:data, :map, default: %{})
      add(:exec_session_sequence, :bigint)

      add(:timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :session_id,
        references(:forge_sessions,
          column: :id,
          name: "forge_events_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:forge_checkpoints, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:sprites_checkpoint_id, :text)
      add(:exec_session_sequence, :bigint)
      add(:runner_state_snapshot, :map)
      add(:metadata, :map, default: %{})

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :session_id,
        references(:forge_sessions,
          column: :id,
          name: "forge_checkpoints_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:forge_checkpoints, "forge_checkpoints_session_id_fkey"))

    drop(table(:forge_checkpoints))

    drop(constraint(:forge_events, "forge_events_session_id_fkey"))

    drop(table(:forge_events))

    drop(constraint(:forge_exec_sessions, "forge_exec_sessions_session_id_fkey"))

    drop(table(:forge_exec_sessions))

    drop(table(:forge_sessions))
  end
end
