defmodule JidoClaw.Repo.Migrations.ToolCallApprovalCases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_cases) do
      modify :workflow_run_id, :uuid, null: true

      add :session_id,
          references(:conversation_sessions,
            column: :id,
            name: "agent_cases_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :fingerprint, :text
      add :tool_name, :text
      add :consumed_at, :utc_datetime_usec
    end

    create index(:agent_cases, [:tenant_id, :fingerprint])

    create index(:agent_cases, [:tenant_id, :fingerprint],
             name: "agent_cases_pending_fingerprint_index",
             unique: true,
             where: "status = 'pending'"
           )
  end

  def down do
    drop constraint(:agent_cases, "agent_cases_session_id_fkey")

    drop_if_exists index(:agent_cases, [:tenant_id, :fingerprint],
                     name: "agent_cases_pending_fingerprint_index"
                   )

    drop_if_exists index(:agent_cases, [:tenant_id, :fingerprint])

    alter table(:agent_cases) do
      remove :consumed_at
      remove :tool_name
      remove :fingerprint
      remove :session_id
      modify :workflow_run_id, :uuid, null: false
    end
  end
end
