defmodule JidoClaw.Repo.Migrations.AddPipelineIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(index(:reasoning_outcomes, [:pipeline_name, :pipeline_stage]))
  end

  def down do
    drop_if_exists(index(:reasoning_outcomes, [:pipeline_name, :pipeline_stage]))
  end
end
