defmodule JidoClaw.Repo.Migrations.AddTraceRunUpdatedAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:trace_runs, [:updated_at])
  end

  def down do
    drop_if_exists index(:trace_runs, [:updated_at])
  end
end
