defmodule JidoClaw.Repo.Migrations.AddCompactionIdentityToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :agent_id, :text, null: false, default: "main"
      add :subagent, :boolean, null: false, default: false
    end

    create index(:messages, [:tenant_id, :session_id, :agent_id, :sequence])

    alter table(:request_correlations) do
      add :agent_id, :text, null: false, default: "main"
      add :subagent, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:request_correlations) do
      remove :subagent
      remove :agent_id
    end

    drop_if_exists index(:messages, [:tenant_id, :session_id, :agent_id, :sequence])

    alter table(:messages) do
      remove :subagent
      remove :agent_id
    end
  end
end
