defmodule JidoClaw.Repo.Migrations.AddWorkflowRunParentLineage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_runs) do
      add :parent_run_id,
          references(:workflow_runs,
            column: :id,
            name: "workflow_runs_parent_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:workflow_runs, [:tenant_id, :parent_run_id])
  end

  def down do
    drop constraint(:workflow_runs, "workflow_runs_parent_run_id_fkey")

    drop_if_exists index(:workflow_runs, [:tenant_id, :parent_run_id])

    alter table(:workflow_runs) do
      remove :parent_run_id
    end
  end
end
