defmodule JidoClaw.Repo.Migrations.AddWorkflowEventLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "workflow_events_tenant_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false

      add :seq, :bigint, null: false
      add :kind, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_run_id,
          references(:workflow_runs,
            column: :id,
            name: "workflow_events_workflow_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:workflow_events, [:tenant_id, :workflow_run_id, :seq], unique: true)
  end

  def down do
    drop constraint(:workflow_events, "workflow_events_tenant_id_fkey")

    drop constraint(:workflow_events, "workflow_events_workflow_run_id_fkey")

    drop_if_exists index(:workflow_events, [:tenant_id, :workflow_run_id, :seq])

    drop table(:workflow_events)
  end
end
