defmodule JidoClaw.Repo.Migrations.AddHumanGates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Greenfield removal of the orphaned `ApprovalGate` resource, replaced by
    # `AgentCase`. `DROP TABLE` also drops the table's own FK constraints and
    # indexes; nothing else references it.
    drop_if_exists table(:approval_gates)

    create table(:agent_cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "agent_cases_tenant_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false

      add :step_name, :text, null: false
      add :kind, :text, null: false
      add :gate_module, :text
      add :status, :text, null: false, default: "pending"
      add :details, :map, default: %{}
      add :decision, :text
      add :decided_by_id, :uuid
      add :decided_at, :utc_datetime_usec
      add :decision_comment, :text
      add :cancellation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_run_id,
          references(:workflow_runs,
            column: :id,
            name: "agent_cases_workflow_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:agent_cases, [:tenant_id, :workflow_run_id, :status])

    create index(:agent_cases, [:tenant_id, :status])

    alter table(:workflow_runs) do
      add :resume_checkpoint, :binary
    end
  end

  def down do
    alter table(:workflow_runs) do
      remove :resume_checkpoint
    end

    drop constraint(:agent_cases, "agent_cases_tenant_id_fkey")

    drop constraint(:agent_cases, "agent_cases_workflow_run_id_fkey")

    drop_if_exists index(:agent_cases, [:tenant_id, :status])

    drop_if_exists index(:agent_cases, [:tenant_id, :workflow_run_id, :status])

    drop table(:agent_cases)

    # Reverse the orphaned-table drop by recreating `approval_gates` in its
    # final pre-removal shape (base columns + requested_by_id FK/index +
    # workflow_run_id FK).
    create table(:approval_gates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :step_name, :text, null: false
      add :reason, :text
      add :status, :text, null: false, default: "pending"
      add :approver_id, :uuid

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "approval_gates_requested_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :comment, :text
      add :decided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_run_id,
          references(:workflow_runs,
            column: :id,
            name: "approval_gates_workflow_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:approval_gates, [:requested_by_id])
  end
end
