defmodule JidoClaw.Repo.Migrations.V060CreateMessagesAndRequestCorrelations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:request_correlations, primary_key: false) do
      add(:request_id, :text, null: false, primary_key: true)

      add(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "request_correlations_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:tenant_id, :text, null: false)

      add(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "request_correlations_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:user_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:expires_at, :utc_datetime_usec, null: false)
    end

    create(index(:request_correlations, [:tenant_id, :expires_at]))

    create(index(:request_correlations, [:expires_at]))

    create table(:messages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "messages_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:tenant_id, :text, null: false)
      add(:request_id, :text)
      add(:role, :text, null: false)
      add(:sequence, :bigint, null: false)
      add(:content, :text)
      add(:metadata, :map, default: %{})
      add(:tool_call_id, :text)

      add(
        :parent_message_id,
        references(:messages,
          column: :id,
          name: "messages_parent_message_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:import_hash, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:messages, [:tenant_id, :session_id]))

    create(index(:messages, [:parent_message_id], where: "parent_message_id IS NOT NULL"))

    create(index(:messages, [:tool_call_id], where: "tool_call_id IS NOT NULL"))

    create(index(:messages, [:session_id, :role]))

    create(index(:messages, [:request_id]))

    create(index(:messages, [:session_id, :sequence]))

    create(
      unique_index(:messages, [:session_id, :import_hash],
        name: "messages_unique_import_hash_index",
        where: "(import_hash IS NOT NULL)"
      )
    )

    create(
      unique_index(:messages, [:session_id, :request_id, :tool_call_id, :role],
        name: "messages_unique_live_tool_row_index",
        where: "(request_id IS NOT NULL AND role IN ('tool_call', 'tool_result'))"
      )
    )

    create(
      unique_index(:messages, [:session_id, :sequence],
        name: "messages_unique_session_sequence_index"
      )
    )
  end

  def down do
    drop(constraint(:messages, "messages_session_id_fkey"))

    drop(constraint(:messages, "messages_parent_message_id_fkey"))

    drop_if_exists(
      unique_index(:messages, [:session_id, :sequence],
        name: "messages_unique_session_sequence_index"
      )
    )

    drop_if_exists(
      unique_index(:messages, [:session_id, :request_id, :tool_call_id, :role],
        name: "messages_unique_live_tool_row_index"
      )
    )

    drop_if_exists(
      unique_index(:messages, [:session_id, :import_hash],
        name: "messages_unique_import_hash_index"
      )
    )

    drop_if_exists(index(:messages, [:session_id, :sequence]))

    drop_if_exists(index(:messages, [:request_id]))

    drop_if_exists(index(:messages, [:session_id, :role]))

    drop_if_exists(index(:messages, [:tool_call_id]))

    drop_if_exists(index(:messages, [:parent_message_id]))

    drop_if_exists(index(:messages, [:tenant_id, :session_id]))

    drop(table(:messages))

    drop(constraint(:request_correlations, "request_correlations_session_id_fkey"))

    drop(constraint(:request_correlations, "request_correlations_workspace_id_fkey"))

    drop_if_exists(index(:request_correlations, [:expires_at]))

    drop_if_exists(index(:request_correlations, [:tenant_id, :expires_at]))

    drop(table(:request_correlations))
  end
end
