defmodule JidoClaw.Repo.Migrations.V060OutcomeSiblingFks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reasoning_outcomes) do
      add(
        :workspace_uuid,
        references(:workspaces,
          column: :id,
          name: "reasoning_outcomes_workspace_uuid_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :session_uuid,
        references(:conversation_sessions,
          column: :id,
          name: "reasoning_outcomes_session_uuid_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(index(:reasoning_outcomes, [:session_uuid, :started_at]))

    create(index(:reasoning_outcomes, [:workspace_uuid, :started_at]))
  end

  def down do
    drop(constraint(:reasoning_outcomes, "reasoning_outcomes_workspace_uuid_fkey"))

    drop(constraint(:reasoning_outcomes, "reasoning_outcomes_session_uuid_fkey"))

    drop_if_exists(index(:reasoning_outcomes, [:workspace_uuid, :started_at]))

    drop_if_exists(index(:reasoning_outcomes, [:session_uuid, :started_at]))

    alter table(:reasoning_outcomes) do
      remove(:session_uuid)
      remove(:workspace_uuid)
    end
  end
end
