defmodule JidoClaw.Repo.Migrations.AddMissingTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and hand-edited to backfill the new timestamp columns from existing
  domain timestamps (rather than letting them all default to migration-run
  time on tables with historical rows).
  """

  use Ecto.Migration

  def up do
    alter table(:reasoning_outcomes) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute """
            UPDATE reasoning_outcomes
            SET inserted_at = started_at,
                updated_at = COALESCE(completed_at, started_at)
            """,
            ""

    alter table(:forge_checkpoints) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "UPDATE forge_checkpoints SET updated_at = created_at", ""

    alter table(:forge_events) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "UPDATE forge_events SET updated_at = timestamp", ""

    alter table(:request_correlations) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "UPDATE request_correlations SET updated_at = inserted_at", ""
  end

  def down do
    alter table(:request_correlations) do
      remove :updated_at
    end

    alter table(:forge_events) do
      remove :updated_at
    end

    alter table(:forge_checkpoints) do
      remove :updated_at
    end

    alter table(:reasoning_outcomes) do
      remove :updated_at
      remove :inserted_at
    end
  end
end
