defmodule JidoClaw.Repo.Migrations.T22AgentviewCompletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # These FKs add `null: false` tenant_id/workspace_id to pre-existing
    # forge_sessions / workflow_runs rows, which would fail on a populated DB.
    # The parents' FK children are all `ON DELETE NO ACTION`, so a bare
    # `DELETE FROM` on the parents would be rejected — `TRUNCATE ... CASCADE`
    # clears parents and children together. These are ephemeral runtime /
    # history tables (sandbox sessions, exec/event/checkpoint logs, workflow
    # runs/steps, approval gates); discarding their rows on this migration is
    # acceptable. No-op on an empty DB.
    execute(
      "TRUNCATE forge_events, forge_checkpoints, forge_exec_sessions, forge_sessions, approval_gates, workflow_steps, workflow_runs CASCADE"
    )

    alter table(:workflow_runs) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "workflow_runs_tenant_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false
    end

    create index(:workflow_runs, [:tenant_id, :completed_at])

    create index(:workflow_runs, [:tenant_id, :status])

    drop constraint(:forge_checkpoints, "forge_checkpoints_session_id_fkey")

    alter table(:forge_checkpoints) do
      modify :session_id,
             references(:forge_sessions,
               column: :id,
               name: "forge_checkpoints_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:forge_events, "forge_events_session_id_fkey")

    alter table(:forge_events) do
      modify :session_id,
             references(:forge_sessions,
               column: :id,
               name: "forge_events_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:approval_gates, "approval_gates_workflow_run_id_fkey")

    alter table(:approval_gates) do
      modify :workflow_run_id,
             references(:workflow_runs,
               column: :id,
               name: "approval_gates_workflow_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:forge_sessions) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "forge_sessions_tenant_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "forge_sessions_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:forge_sessions, [:tenant_id, :workspace_id, :phase])

    drop constraint(:forge_exec_sessions, "forge_exec_sessions_session_id_fkey")

    alter table(:forge_exec_sessions) do
      modify :session_id,
             references(:forge_sessions,
               column: :id,
               name: "forge_exec_sessions_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:workflow_steps, "workflow_steps_workflow_run_id_fkey")

    alter table(:workflow_steps) do
      modify :workflow_run_id,
             references(:workflow_runs,
               column: :id,
               name: "workflow_steps_workflow_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:workflow_steps, "workflow_steps_workflow_run_id_fkey")

    alter table(:workflow_steps) do
      modify :workflow_run_id,
             references(:workflow_runs,
               column: :id,
               name: "workflow_steps_workflow_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:forge_exec_sessions, "forge_exec_sessions_session_id_fkey")

    alter table(:forge_exec_sessions) do
      modify :session_id,
             references(:forge_sessions,
               column: :id,
               name: "forge_exec_sessions_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:forge_sessions, "forge_sessions_tenant_id_fkey")

    drop constraint(:forge_sessions, "forge_sessions_workspace_id_fkey")

    drop_if_exists index(:forge_sessions, [:tenant_id, :workspace_id, :phase])

    alter table(:forge_sessions) do
      remove :workspace_id
      remove :tenant_id
    end

    drop constraint(:approval_gates, "approval_gates_workflow_run_id_fkey")

    alter table(:approval_gates) do
      modify :workflow_run_id,
             references(:workflow_runs,
               column: :id,
               name: "approval_gates_workflow_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:forge_events, "forge_events_session_id_fkey")

    alter table(:forge_events) do
      modify :session_id,
             references(:forge_sessions,
               column: :id,
               name: "forge_events_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:forge_checkpoints, "forge_checkpoints_session_id_fkey")

    alter table(:forge_checkpoints) do
      modify :session_id,
             references(:forge_sessions,
               column: :id,
               name: "forge_checkpoints_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:workflow_runs, "workflow_runs_tenant_id_fkey")

    drop_if_exists index(:workflow_runs, [:tenant_id, :status])

    drop_if_exists index(:workflow_runs, [:tenant_id, :completed_at])

    alter table(:workflow_runs) do
      remove :tenant_id
    end
  end
end
