defmodule JidoClaw.Repo.Migrations.AddCronTargetAndCounters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cron_jobs) do
      add :target, :text, null: false, default: "agent"
      add :workflow_name, :text
      add :workflow_input, :map, default: %{}
      add :run_count, :bigint, null: false, default: 0
      add :last_run_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:cron_jobs) do
      remove :last_run_at
      remove :run_count
      remove :workflow_input
      remove :workflow_name
      remove :target
    end
  end
end
