defmodule JidoClaw.Repo.Migrations.CreateOrchestrationTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_steps, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:step_type, :text)
      add(:sequence, :bigint, null: false, default: 0)
      add(:status, :text, null: false, default: "pending")
      add(:config, :map, default: %{})
      add(:output, :map)
      add(:error, :text)
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:workflow_run_id, :uuid, null: false)
    end

    create table(:workflow_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:workflow_steps) do
      modify(
        :workflow_run_id,
        references(:workflow_runs,
          column: :id,
          name: "workflow_steps_workflow_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflow_runs) do
      add(:name, :text, null: false)
      add(:workflow_type, :text)
      add(:status, :text, null: false, default: "pending")
      add(:config, :map, default: %{})
      add(:result, :map)
      add(:error, :text)
      add(:retry_of_id, :uuid)
      add(:user_id, :uuid)
      add(:project_id, :uuid)
      add(:metadata, :map, default: %{})
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:approval_gates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:step_name, :text, null: false)
      add(:reason, :text)
      add(:status, :text, null: false, default: "pending")
      add(:approver_id, :uuid)
      add(:requested_by_id, :uuid)
      add(:comment, :text)
      add(:decided_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_run_id,
        references(:workflow_runs,
          column: :id,
          name: "approval_gates_workflow_run_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:approval_gates, "approval_gates_workflow_run_id_fkey"))

    drop(table(:approval_gates))

    alter table(:workflow_runs) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:completed_at)
      remove(:started_at)
      remove(:metadata)
      remove(:project_id)
      remove(:user_id)
      remove(:retry_of_id)
      remove(:error)
      remove(:result)
      remove(:config)
      remove(:status)
      remove(:workflow_type)
      remove(:name)
    end

    drop(constraint(:workflow_steps, "workflow_steps_workflow_run_id_fkey"))

    alter table(:workflow_steps) do
      modify(:workflow_run_id, :uuid)
    end

    drop(table(:workflow_runs))

    drop(table(:workflow_steps))
  end
end
