defmodule JidoClaw.Repo.Migrations.V064AuditTenant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:messages, [:request_id, :role], name: "messages_request_id_role_idx"))

    drop_if_exists(index(:messages, [:tenant_id, :session_id]))

    drop_if_exists(index(:messages, [:parent_message_id]))

    drop_if_exists(index(:messages, [:tool_call_id]))

    drop_if_exists(index(:messages, [:session_id, :role]))

    drop_if_exists(index(:messages, [:request_id]))

    drop_if_exists(index(:messages, [:session_id, :sequence]))

    create(
      index(:messages, [:tenant_id, :request_id, :role],
        name: "messages_request_id_role_idx",
        where: "request_id IS NOT NULL"
      )
    )

    create(index(:messages, [:tenant_id, :session_id]))

    create(
      index(:messages, [:tenant_id, :parent_message_id], where: "parent_message_id IS NOT NULL")
    )

    create(index(:messages, [:tenant_id, :tool_call_id], where: "tool_call_id IS NOT NULL"))

    create(index(:messages, [:tenant_id, :session_id, :role]))

    create(index(:messages, [:tenant_id, :request_id]))

    create(index(:messages, [:tenant_id, :session_id, :sequence]))

    drop(constraint(:messages, "messages_parent_message_id_fkey"))

    drop(constraint(:messages, "messages_session_id_fkey"))

    drop_if_exists(
      unique_index(:messages, [:session_id, :import_hash],
        name: "messages_unique_import_hash_index"
      )
    )

    drop_if_exists(
      unique_index(:messages, [:session_id, :request_id, :tool_call_id, :role],
        name: "messages_unique_live_tool_row_index"
      )
    )

    drop_if_exists(
      unique_index(:messages, [:session_id, :sequence],
        name: "messages_unique_session_sequence_index"
      )
    )

    create(
      unique_index(:messages, [:tenant_id, :session_id, :import_hash],
        name: "messages_unique_import_hash_index",
        where: "(import_hash IS NOT NULL)"
      )
    )

    create(
      unique_index(:messages, [:tenant_id, :session_id, :request_id, :tool_call_id, :role],
        name: "messages_unique_live_tool_row_index",
        where: "(request_id IS NOT NULL AND role IN ('tool_call', 'tool_result'))"
      )
    )

    create(
      unique_index(:messages, [:tenant_id, :session_id, :sequence],
        name: "messages_unique_session_sequence_index"
      )
    )

    alter table(:messages) do
      modify(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "messages_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:reasoning_outcomes, "reasoning_outcomes_session_uuid_fkey"))

    drop(constraint(:reasoning_outcomes, "reasoning_outcomes_workspace_uuid_fkey"))

    alter table(:reasoning_outcomes) do
      modify(
        :workspace_uuid,
        references(:workspaces,
          column: :id,
          name: "reasoning_outcomes_workspace_uuid_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :session_uuid,
        references(:conversation_sessions,
          column: :id,
          name: "reasoning_outcomes_session_uuid_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:solutions, [:search_vector]))

    drop_if_exists(index(:solutions, [:tenant_id, :embedding_status]))

    drop_if_exists(index(:solutions, [:tenant_id, :trust_score]))

    drop_if_exists(index(:solutions, [:tenant_id, :sharing]))

    drop_if_exists(index(:solutions, [:tenant_id, :agent_id]))

    drop_if_exists(index(:solutions, [:tenant_id, :language, :framework]))

    drop_if_exists(index(:solutions, [:tenant_id, :workspace_id]))

    drop_if_exists(index(:solutions, [:tenant_id, :problem_signature]))

    create(index(:solutions, [:search_vector], using: "gin"))

    create(index(:solutions, [:tenant_id, :embedding_status]))

    create(index(:solutions, [:tenant_id, :trust_score]))

    create(index(:solutions, [:tenant_id, :sharing]))

    create(index(:solutions, [:tenant_id, :agent_id]))

    create(index(:solutions, [:tenant_id, :language, :framework]))

    create(index(:solutions, [:tenant_id, :workspace_id]))

    create(index(:solutions, [:tenant_id, :problem_signature]))

    drop(constraint(:solutions, "solutions_session_id_fkey"))

    drop(constraint(:solutions, "solutions_workspace_id_fkey"))

    alter table(:solutions) do
      modify(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "solutions_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "solutions_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:memory_links, [:tenant_id, :to_fact_id, :relation]))

    drop_if_exists(index(:memory_links, [:tenant_id, :from_fact_id, :relation]))

    create(index(:memory_links, [:tenant_id, :to_fact_id, :relation]))

    create(index(:memory_links, [:tenant_id, :from_fact_id, :relation]))

    drop(constraint(:memory_links, "memory_links_to_fact_id_fkey"))

    drop(constraint(:memory_links, "memory_links_from_fact_id_fkey"))

    drop_if_exists(
      unique_index(:memory_links, [:from_fact_id, :to_fact_id, :relation],
        name: "memory_links_unique_edge_index"
      )
    )

    create(
      unique_index(:memory_links, [:tenant_id, :from_fact_id, :to_fact_id, :relation],
        name: "memory_links_unique_edge_index"
      )
    )

    alter table(:memory_links) do
      modify(
        :from_fact_id,
        references(:memory_facts,
          column: :id,
          name: "memory_links_from_fact_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :to_fact_id,
        references(:memory_facts,
          column: :id,
          name: "memory_links_to_fact_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(
      unique_index(:reputation_imports, [:tenant_id, :source_sha256],
        name: "reputation_imports_unique_tenant_source_index"
      )
    )

    create(
      unique_index(:reputation_imports, [:tenant_id, :source_sha256],
        name: "reputation_imports_unique_tenant_source_index"
      )
    )

    create table(:audit_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:event_kind, :text, null: false)
      add(:actor_kind, :text, null: false)
      add(:actor_id, :text)
      add(:target_kind, :text)
      add(:target_id, :text)
      add(:payload, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:audit_events, [:tenant_id, :target_kind, :target_id, :inserted_at]))

    create(index(:audit_events, [:tenant_id, :actor_kind, :actor_id, :inserted_at]))

    create(index(:audit_events, [:tenant_id, :event_kind, :inserted_at]))

    drop_if_exists(index(:workspaces, [:tenant_id, :user_id, :path]))

    create(index(:workspaces, [:tenant_id, :user_id, :path]))

    drop_if_exists(
      unique_index(:workspaces, [:tenant_id, :user_id, :path],
        name: "workspaces_unique_user_path_authed_index"
      )
    )

    drop_if_exists(
      unique_index(:workspaces, [:tenant_id, :path],
        name: "workspaces_unique_user_path_cli_index"
      )
    )

    create(
      unique_index(:workspaces, [:tenant_id, :user_id, :path],
        name: "workspaces_unique_user_path_authed_index",
        where: "(user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:workspaces, [:tenant_id, :path],
        name: "workspaces_unique_user_path_cli_index",
        where: "(user_id IS NULL)"
      )
    )

    drop_if_exists(index(:request_correlations, [:tenant_id, :expires_at]))

    drop_if_exists(index(:request_correlations, [:expires_at]))

    create(index(:request_correlations, [:tenant_id, :expires_at]))

    create(index(:request_correlations, [:expires_at]))

    drop(constraint(:request_correlations, "request_correlations_workspace_id_fkey"))

    drop(constraint(:request_correlations, "request_correlations_session_id_fkey"))

    alter table(:request_correlations) do
      modify(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "request_correlations_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:conversation_sessions, [:tenant_id, :last_active_at]))

    drop_if_exists(index(:conversation_sessions, [:workspace_id, :started_at]))

    create(index(:conversation_sessions, [:tenant_id, :last_active_at]))

    create(index(:conversation_sessions, [:tenant_id, :workspace_id, :started_at]))

    drop(constraint(:conversation_sessions, "conversation_sessions_workspace_id_fkey"))

    drop_if_exists(
      unique_index(:conversation_sessions, [:tenant_id, :workspace_id, :kind, :external_id],
        name: "conversation_sessions_unique_external_index"
      )
    )

    create(
      unique_index(:conversation_sessions, [:tenant_id, :workspace_id, :kind, :external_id],
        name: "conversation_sessions_unique_external_index"
      )
    )

    alter table(:conversation_sessions) do
      modify(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "conversation_sessions_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:memory_facts, [:tenant_id, :embedding_status]))

    drop_if_exists(index(:memory_facts, [:search_vector]))

    drop_if_exists(index(:memory_facts, [:tenant_id, :source, :inserted_at]))

    drop_if_exists(index(:memory_facts, [:tenant_id, :scope_kind, :valid_at]))

    create(index(:memory_facts, [:tenant_id, :embedding_status]))

    create(index(:memory_facts, [:search_vector], using: "gin"))

    create(index(:memory_facts, [:tenant_id, :source, :inserted_at]))

    create(index(:memory_facts, [:tenant_id, :scope_kind, :valid_at]))

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :label],
        name: "memory_facts_unique_active_label_per_scope_project_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :label],
        name: "memory_facts_unique_active_label_per_scope_session_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :label],
        name: "memory_facts_unique_active_label_per_scope_user_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :label],
        name: "memory_facts_unique_active_label_per_scope_workspace_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :content_hash],
        name: "mf_promoted_proj_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :content_hash],
        name: "mf_promoted_sess_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :content_hash],
        name: "mf_promoted_user_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :content_hash],
        name: "mf_promoted_ws_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:import_hash], name: "memory_facts_unique_import_hash_index")
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :label],
        name: "memory_facts_unique_active_label_per_scope_project_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND project_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :label],
        name: "memory_facts_unique_active_label_per_scope_session_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND session_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :label],
        name: "memory_facts_unique_active_label_per_scope_user_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :label],
        name: "memory_facts_unique_active_label_per_scope_workspace_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND workspace_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :content_hash],
        name: "mf_promoted_proj_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND project_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :content_hash],
        name: "mf_promoted_sess_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND session_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :content_hash],
        name: "mf_promoted_user_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :content_hash],
        name: "mf_promoted_ws_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND workspace_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :import_hash],
        name: "memory_facts_unique_import_hash_index",
        where: "(import_hash IS NOT NULL)"
      )
    )

    drop_if_exists(index(:memory_consolidation_runs, [:forge_session_id]))

    drop_if_exists(index(:memory_consolidation_runs, [:tenant_id, :status, :started_at]))

    drop_if_exists(index(:memory_consolidation_runs, [:tenant_id, :scope_kind, :started_at]))

    create(
      index(:memory_consolidation_runs, [:tenant_id, :forge_session_id],
        where: "forge_session_id IS NOT NULL"
      )
    )

    create(index(:memory_consolidation_runs, [:tenant_id, :status, :started_at]))

    create(index(:memory_consolidation_runs, [:tenant_id, :scope_kind, :started_at]))

    drop_if_exists(index(:memory_episodes, [:tenant_id, :source_solution_id]))

    drop_if_exists(index(:memory_episodes, [:tenant_id, :source_message_id]))

    drop_if_exists(index(:memory_episodes, [:tenant_id, :scope_kind, :inserted_at]))

    create(
      index(:memory_episodes, [:tenant_id, :source_solution_id],
        where: "source_solution_id IS NOT NULL"
      )
    )

    create(
      index(:memory_episodes, [:tenant_id, :source_message_id],
        where: "source_message_id IS NOT NULL"
      )
    )

    create(index(:memory_episodes, [:tenant_id, :scope_kind, :inserted_at]))

    create table(:cron_jobs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:job_id, :text, null: false)
      add(:task, :text)
      add(:mode, :text, null: false, default: "main")
      add(:schedule_kind, :text, null: false)
      add(:schedule_value, :text, null: false)
      add(:mfa_module, :text)
      add(:mfa_function, :text)
      add(:mfa_args, :map, default: %{})
      add(:disabled_at, :utc_datetime_usec)
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:cron_jobs, [:tenant_id, :disabled_at]))

    create(unique_index(:cron_jobs, [:tenant_id, :job_id], name: "cron_jobs_unique_job_index"))

    drop_if_exists(index(:reputations, [:tenant_id, :score]))

    create(index(:reputations, [:tenant_id, :score]))

    drop_if_exists(
      unique_index(:reputations, [:tenant_id, :agent_id],
        name: "reputations_unique_tenant_agent_index"
      )
    )

    create(
      unique_index(:reputations, [:tenant_id, :agent_id],
        name: "reputations_unique_tenant_agent_index"
      )
    )

    drop_if_exists(index(:memory_block_revisions, [:tenant_id, :scope_kind, :inserted_at]))

    drop_if_exists(index(:memory_block_revisions, [:block_id, :inserted_at]))

    create(index(:memory_block_revisions, [:tenant_id, :scope_kind, :inserted_at]))

    create(index(:memory_block_revisions, [:tenant_id, :block_id, :inserted_at]))

    drop(constraint(:memory_block_revisions, "memory_block_revisions_block_id_fkey"))

    alter table(:memory_block_revisions) do
      modify(
        :block_id,
        references(:memory_blocks,
          column: :id,
          name: "memory_block_revisions_block_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:tenants, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
    end

    alter table(:messages) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "messages_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      modify(
        :parent_message_id,
        references(:messages,
          column: :id,
          name: "messages_parent_message_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(index(:messages, [:tenant_id]))

    alter table(:solutions) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "solutions_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:solutions, [:tenant_id]))

    alter table(:memory_links) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_links_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_links, [:tenant_id]))

    alter table(:reputation_imports) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "reputation_imports_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:reputation_imports, [:tenant_id]))

    alter table(:audit_events) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "audit_events_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:workspaces) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "workspaces_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:workspaces, [:tenant_id]))

    alter table(:request_correlations) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "request_correlations_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      modify(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "request_correlations_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(index(:request_correlations, [:tenant_id]))

    alter table(:conversation_sessions) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "conversation_sessions_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:conversation_sessions, [:tenant_id]))

    alter table(:memory_facts) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_facts_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_facts, [:tenant_id]))

    alter table(:memory_consolidation_runs) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_consolidation_runs_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_consolidation_runs, [:tenant_id]))

    alter table(:memory_episodes) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_episodes_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_episodes, [:tenant_id]))

    alter table(:cron_jobs) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "cron_jobs_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:reputations) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "reputations_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:reputations, [:tenant_id]))

    alter table(:memory_block_revisions) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_block_revisions_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_block_revisions, [:tenant_id]))

    alter table(:tenants) do
      add(:name, :text, null: false, default: "default")
      add(:status, :text, null: false, default: "active")
      add(:config, :map, null: false, default: %{})
      add(:archived_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    drop_if_exists(index(:memory_fact_episodes, [:tenant_id, :inserted_at]))

    drop_if_exists(index(:memory_fact_episodes, [:episode_id]))

    drop_if_exists(index(:memory_fact_episodes, [:fact_id, :role]))

    create(index(:memory_fact_episodes, [:tenant_id, :inserted_at]))

    create(index(:memory_fact_episodes, [:tenant_id, :episode_id]))

    create(index(:memory_fact_episodes, [:tenant_id, :fact_id, :role]))

    drop(constraint(:memory_fact_episodes, "memory_fact_episodes_episode_id_fkey"))

    drop(constraint(:memory_fact_episodes, "memory_fact_episodes_fact_id_fkey"))

    drop_if_exists(
      unique_index(:memory_fact_episodes, [:fact_id, :episode_id],
        name: "memory_fact_episodes_unique_pair_index"
      )
    )

    create(
      unique_index(:memory_fact_episodes, [:tenant_id, :fact_id, :episode_id],
        name: "memory_fact_episodes_unique_pair_index"
      )
    )

    alter table(:memory_fact_episodes) do
      modify(
        :fact_id,
        references(:memory_facts,
          column: :id,
          name: "memory_fact_episodes_fact_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :episode_id,
        references(:memory_episodes,
          column: :id,
          name: "memory_fact_episodes_episode_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_fact_episodes_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_fact_episodes, [:tenant_id]))

    drop_if_exists(index(:memory_blocks, [:tenant_id, :source, :inserted_at]))

    drop_if_exists(index(:memory_blocks, [:tenant_id, :scope_kind, :label, :invalid_at]))

    create(index(:memory_blocks, [:tenant_id, :source, :inserted_at]))

    create(index(:memory_blocks, [:tenant_id, :scope_kind, :label, :invalid_at]))

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :project_id],
        name: "memory_blocks_unique_label_per_scope_project_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :session_id],
        name: "memory_blocks_unique_label_per_scope_session_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :user_id],
        name: "memory_blocks_unique_label_per_scope_user_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :workspace_id],
        name: "memory_blocks_unique_label_per_scope_workspace_index"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :project_id],
        name: "memory_blocks_unique_label_per_scope_project_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND project_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :session_id],
        name: "memory_blocks_unique_label_per_scope_session_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND session_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :user_id],
        name: "memory_blocks_unique_label_per_scope_user_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :workspace_id],
        name: "memory_blocks_unique_label_per_scope_workspace_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND workspace_id IS NOT NULL)"
      )
    )

    alter table(:memory_blocks) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "memory_blocks_tenant_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:memory_blocks, [:tenant_id]))
  end

  def down do
    drop_if_exists(index(:memory_blocks, [:tenant_id]))

    drop(constraint(:memory_blocks, "memory_blocks_tenant_id_fkey"))

    alter table(:memory_blocks) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :workspace_id],
        name: "memory_blocks_unique_label_per_scope_workspace_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :user_id],
        name: "memory_blocks_unique_label_per_scope_user_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :session_id],
        name: "memory_blocks_unique_label_per_scope_session_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :project_id],
        name: "memory_blocks_unique_label_per_scope_project_index"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :workspace_id],
        name: "memory_blocks_unique_label_per_scope_workspace_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND workspace_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :user_id],
        name: "memory_blocks_unique_label_per_scope_user_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :session_id],
        name: "memory_blocks_unique_label_per_scope_session_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND session_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_blocks, [:tenant_id, :scope_kind, :label, :project_id],
        name: "memory_blocks_unique_label_per_scope_project_index",
        where: "(invalid_at IS NULL AND tenant_id IS NOT NULL AND project_id IS NOT NULL)"
      )
    )

    drop_if_exists(index(:memory_blocks, [:tenant_id, :scope_kind, :label, :invalid_at]))

    drop_if_exists(index(:memory_blocks, [:tenant_id, :source, :inserted_at]))

    create(index(:memory_blocks, [:tenant_id, :scope_kind, :label, :invalid_at]))

    create(index(:memory_blocks, [:tenant_id, :source, :inserted_at]))

    drop_if_exists(index(:memory_fact_episodes, [:tenant_id]))

    drop(constraint(:memory_fact_episodes, "memory_fact_episodes_fact_id_fkey"))

    drop(constraint(:memory_fact_episodes, "memory_fact_episodes_episode_id_fkey"))

    drop(constraint(:memory_fact_episodes, "memory_fact_episodes_tenant_id_fkey"))

    alter table(:memory_fact_episodes) do
      modify(:tenant_id, :text)

      modify(
        :episode_id,
        references(:memory_episodes,
          column: :id,
          name: "memory_fact_episodes_episode_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :fact_id,
        references(:memory_facts,
          column: :id,
          name: "memory_fact_episodes_fact_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(
      unique_index(:memory_fact_episodes, [:tenant_id, :fact_id, :episode_id],
        name: "memory_fact_episodes_unique_pair_index"
      )
    )

    create(
      unique_index(:memory_fact_episodes, [:fact_id, :episode_id],
        name: "memory_fact_episodes_unique_pair_index"
      )
    )

    drop_if_exists(index(:memory_fact_episodes, [:tenant_id, :fact_id, :role]))

    drop_if_exists(index(:memory_fact_episodes, [:tenant_id, :episode_id]))

    drop_if_exists(index(:memory_fact_episodes, [:tenant_id, :inserted_at]))

    create(index(:memory_fact_episodes, [:fact_id, :role]))

    create(index(:memory_fact_episodes, [:episode_id]))

    create(index(:memory_fact_episodes, [:tenant_id, :inserted_at]))

    alter table(:tenants) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:archived_at)
      remove(:config)
      remove(:status)
      remove(:name)
    end

    drop_if_exists(index(:memory_block_revisions, [:tenant_id]))

    drop(constraint(:memory_block_revisions, "memory_block_revisions_tenant_id_fkey"))

    alter table(:memory_block_revisions) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:reputations, [:tenant_id]))

    drop(constraint(:reputations, "reputations_tenant_id_fkey"))

    alter table(:reputations) do
      modify(:tenant_id, :text)
    end

    drop(constraint(:cron_jobs, "cron_jobs_tenant_id_fkey"))

    alter table(:cron_jobs) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:memory_episodes, [:tenant_id]))

    drop(constraint(:memory_episodes, "memory_episodes_tenant_id_fkey"))

    alter table(:memory_episodes) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:memory_consolidation_runs, [:tenant_id]))

    drop(constraint(:memory_consolidation_runs, "memory_consolidation_runs_tenant_id_fkey"))

    alter table(:memory_consolidation_runs) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:memory_facts, [:tenant_id]))

    drop(constraint(:memory_facts, "memory_facts_tenant_id_fkey"))

    alter table(:memory_facts) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:conversation_sessions, [:tenant_id]))

    drop(constraint(:conversation_sessions, "conversation_sessions_tenant_id_fkey"))

    alter table(:conversation_sessions) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:request_correlations, [:tenant_id]))

    drop(constraint(:request_correlations, "request_correlations_tenant_id_fkey"))

    drop(constraint(:request_correlations, "request_correlations_workspace_id_fkey"))

    alter table(:request_correlations) do
      modify(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "request_correlations_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:workspaces, [:tenant_id]))

    drop(constraint(:workspaces, "workspaces_tenant_id_fkey"))

    alter table(:workspaces) do
      modify(:tenant_id, :text)
    end

    drop(constraint(:audit_events, "audit_events_tenant_id_fkey"))

    alter table(:audit_events) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:reputation_imports, [:tenant_id]))

    drop(constraint(:reputation_imports, "reputation_imports_tenant_id_fkey"))

    alter table(:reputation_imports) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:memory_links, [:tenant_id]))

    drop(constraint(:memory_links, "memory_links_tenant_id_fkey"))

    alter table(:memory_links) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:solutions, [:tenant_id]))

    drop(constraint(:solutions, "solutions_tenant_id_fkey"))

    alter table(:solutions) do
      modify(:tenant_id, :text)
    end

    drop_if_exists(index(:messages, [:tenant_id]))

    drop(constraint(:messages, "messages_tenant_id_fkey"))

    drop(constraint(:messages, "messages_parent_message_id_fkey"))

    alter table(:messages) do
      modify(
        :parent_message_id,
        references(:messages,
          column: :id,
          name: "messages_parent_message_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(:tenant_id, :text)
    end

    drop(table(:tenants))

    drop(constraint(:memory_block_revisions, "memory_block_revisions_block_id_fkey"))

    alter table(:memory_block_revisions) do
      modify(
        :block_id,
        references(:memory_blocks,
          column: :id,
          name: "memory_block_revisions_block_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:memory_block_revisions, [:tenant_id, :block_id, :inserted_at]))

    drop_if_exists(index(:memory_block_revisions, [:tenant_id, :scope_kind, :inserted_at]))

    create(index(:memory_block_revisions, [:block_id, :inserted_at]))

    create(index(:memory_block_revisions, [:tenant_id, :scope_kind, :inserted_at]))

    drop_if_exists(
      unique_index(:reputations, [:tenant_id, :agent_id],
        name: "reputations_unique_tenant_agent_index"
      )
    )

    create(
      unique_index(:reputations, [:tenant_id, :agent_id],
        name: "reputations_unique_tenant_agent_index"
      )
    )

    drop_if_exists(index(:reputations, [:tenant_id, :score]))

    create(index(:reputations, [:tenant_id, :score]))

    drop_if_exists(
      unique_index(:cron_jobs, [:tenant_id, :job_id], name: "cron_jobs_unique_job_index")
    )

    drop_if_exists(index(:cron_jobs, [:tenant_id, :disabled_at]))

    drop(table(:cron_jobs))

    drop_if_exists(index(:memory_episodes, [:tenant_id, :scope_kind, :inserted_at]))

    drop_if_exists(index(:memory_episodes, [:tenant_id, :source_message_id]))

    drop_if_exists(index(:memory_episodes, [:tenant_id, :source_solution_id]))

    create(index(:memory_episodes, [:tenant_id, :scope_kind, :inserted_at]))

    create(
      index(:memory_episodes, [:tenant_id, :source_message_id],
        where: "source_message_id IS NOT NULL"
      )
    )

    create(
      index(:memory_episodes, [:tenant_id, :source_solution_id],
        where: "source_solution_id IS NOT NULL"
      )
    )

    drop_if_exists(index(:memory_consolidation_runs, [:tenant_id, :scope_kind, :started_at]))

    drop_if_exists(index(:memory_consolidation_runs, [:tenant_id, :status, :started_at]))

    drop_if_exists(index(:memory_consolidation_runs, [:tenant_id, :forge_session_id]))

    create(index(:memory_consolidation_runs, [:tenant_id, :scope_kind, :started_at]))

    create(index(:memory_consolidation_runs, [:tenant_id, :status, :started_at]))

    create(
      index(:memory_consolidation_runs, [:forge_session_id],
        where: "forge_session_id IS NOT NULL"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :import_hash],
        name: "memory_facts_unique_import_hash_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :content_hash],
        name: "mf_promoted_ws_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :content_hash],
        name: "mf_promoted_user_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :content_hash],
        name: "mf_promoted_sess_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :content_hash],
        name: "mf_promoted_proj_idx"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :label],
        name: "memory_facts_unique_active_label_per_scope_workspace_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :label],
        name: "memory_facts_unique_active_label_per_scope_user_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :label],
        name: "memory_facts_unique_active_label_per_scope_session_index"
      )
    )

    drop_if_exists(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :label],
        name: "memory_facts_unique_active_label_per_scope_project_index"
      )
    )

    create(
      unique_index(:memory_facts, [:import_hash],
        name: "memory_facts_unique_import_hash_index",
        where: "(import_hash IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :content_hash],
        name: "mf_promoted_ws_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND workspace_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :content_hash],
        name: "mf_promoted_user_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :content_hash],
        name: "mf_promoted_sess_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND session_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :content_hash],
        name: "mf_promoted_proj_idx",
        where:
          "(source = 'consolidator_promoted' AND invalid_at IS NULL AND content_hash IS NOT NULL AND tenant_id IS NOT NULL AND project_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :workspace_id, :label],
        name: "memory_facts_unique_active_label_per_scope_workspace_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND workspace_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :user_id, :label],
        name: "memory_facts_unique_active_label_per_scope_user_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :session_id, :label],
        name: "memory_facts_unique_active_label_per_scope_session_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND session_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:memory_facts, [:tenant_id, :scope_kind, :project_id, :label],
        name: "memory_facts_unique_active_label_per_scope_project_index",
        where:
          "(label IS NOT NULL AND invalid_at IS NULL AND tenant_id IS NOT NULL AND project_id IS NOT NULL)"
      )
    )

    drop_if_exists(index(:memory_facts, [:tenant_id, :scope_kind, :valid_at]))

    drop_if_exists(index(:memory_facts, [:tenant_id, :source, :inserted_at]))

    drop_if_exists(index(:memory_facts, [:search_vector]))

    drop_if_exists(index(:memory_facts, [:tenant_id, :embedding_status]))

    create(index(:memory_facts, [:tenant_id, :scope_kind, :valid_at]))

    create(index(:memory_facts, [:tenant_id, :source, :inserted_at]))

    create(index(:memory_facts, [:search_vector], using: "gin"))

    create(index(:memory_facts, [:tenant_id, :embedding_status]))

    drop(constraint(:conversation_sessions, "conversation_sessions_workspace_id_fkey"))

    alter table(:conversation_sessions) do
      modify(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "conversation_sessions_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(
      unique_index(:conversation_sessions, [:tenant_id, :workspace_id, :kind, :external_id],
        name: "conversation_sessions_unique_external_index"
      )
    )

    create(
      unique_index(:conversation_sessions, [:tenant_id, :workspace_id, :kind, :external_id],
        name: "conversation_sessions_unique_external_index"
      )
    )

    drop_if_exists(index(:conversation_sessions, [:tenant_id, :workspace_id, :started_at]))

    drop_if_exists(index(:conversation_sessions, [:tenant_id, :last_active_at]))

    create(index(:conversation_sessions, [:workspace_id, :started_at]))

    create(index(:conversation_sessions, [:tenant_id, :last_active_at]))

    drop(constraint(:request_correlations, "request_correlations_session_id_fkey"))

    alter table(:request_correlations) do
      modify(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "request_correlations_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:request_correlations, [:expires_at]))

    drop_if_exists(index(:request_correlations, [:tenant_id, :expires_at]))

    create(index(:request_correlations, [:expires_at]))

    create(index(:request_correlations, [:tenant_id, :expires_at]))

    drop_if_exists(
      unique_index(:workspaces, [:tenant_id, :path],
        name: "workspaces_unique_user_path_cli_index"
      )
    )

    drop_if_exists(
      unique_index(:workspaces, [:tenant_id, :user_id, :path],
        name: "workspaces_unique_user_path_authed_index"
      )
    )

    create(
      unique_index(:workspaces, [:tenant_id, :path],
        name: "workspaces_unique_user_path_cli_index",
        where: "(user_id IS NULL)"
      )
    )

    create(
      unique_index(:workspaces, [:tenant_id, :user_id, :path],
        name: "workspaces_unique_user_path_authed_index",
        where: "(user_id IS NOT NULL)"
      )
    )

    drop_if_exists(index(:workspaces, [:tenant_id, :user_id, :path]))

    create(index(:workspaces, [:tenant_id, :user_id, :path]))

    drop_if_exists(index(:audit_events, [:tenant_id, :event_kind, :inserted_at]))

    drop_if_exists(index(:audit_events, [:tenant_id, :actor_kind, :actor_id, :inserted_at]))

    drop_if_exists(index(:audit_events, [:tenant_id, :target_kind, :target_id, :inserted_at]))

    drop(table(:audit_events))

    drop_if_exists(
      unique_index(:reputation_imports, [:tenant_id, :source_sha256],
        name: "reputation_imports_unique_tenant_source_index"
      )
    )

    create(
      unique_index(:reputation_imports, [:tenant_id, :source_sha256],
        name: "reputation_imports_unique_tenant_source_index"
      )
    )

    drop(constraint(:memory_links, "memory_links_from_fact_id_fkey"))

    drop(constraint(:memory_links, "memory_links_to_fact_id_fkey"))

    alter table(:memory_links) do
      modify(
        :to_fact_id,
        references(:memory_facts,
          column: :id,
          name: "memory_links_to_fact_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :from_fact_id,
        references(:memory_facts,
          column: :id,
          name: "memory_links_from_fact_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(
      unique_index(:memory_links, [:tenant_id, :from_fact_id, :to_fact_id, :relation],
        name: "memory_links_unique_edge_index"
      )
    )

    create(
      unique_index(:memory_links, [:from_fact_id, :to_fact_id, :relation],
        name: "memory_links_unique_edge_index"
      )
    )

    drop_if_exists(index(:memory_links, [:tenant_id, :from_fact_id, :relation]))

    drop_if_exists(index(:memory_links, [:tenant_id, :to_fact_id, :relation]))

    create(index(:memory_links, [:tenant_id, :from_fact_id, :relation]))

    create(index(:memory_links, [:tenant_id, :to_fact_id, :relation]))

    drop(constraint(:solutions, "solutions_workspace_id_fkey"))

    drop(constraint(:solutions, "solutions_session_id_fkey"))

    alter table(:solutions) do
      modify(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "solutions_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "solutions_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:solutions, [:tenant_id, :problem_signature]))

    drop_if_exists(index(:solutions, [:tenant_id, :workspace_id]))

    drop_if_exists(index(:solutions, [:tenant_id, :language, :framework]))

    drop_if_exists(index(:solutions, [:tenant_id, :agent_id]))

    drop_if_exists(index(:solutions, [:tenant_id, :sharing]))

    drop_if_exists(index(:solutions, [:tenant_id, :trust_score]))

    drop_if_exists(index(:solutions, [:tenant_id, :embedding_status]))

    drop_if_exists(index(:solutions, [:search_vector]))

    create(index(:solutions, [:tenant_id, :problem_signature]))

    create(index(:solutions, [:tenant_id, :workspace_id]))

    create(index(:solutions, [:tenant_id, :language, :framework]))

    create(index(:solutions, [:tenant_id, :agent_id]))

    create(index(:solutions, [:tenant_id, :sharing]))

    create(index(:solutions, [:tenant_id, :trust_score]))

    create(index(:solutions, [:tenant_id, :embedding_status]))

    create(index(:solutions, [:search_vector], using: "gin"))

    drop(constraint(:reasoning_outcomes, "reasoning_outcomes_workspace_uuid_fkey"))

    drop(constraint(:reasoning_outcomes, "reasoning_outcomes_session_uuid_fkey"))

    alter table(:reasoning_outcomes) do
      modify(
        :session_uuid,
        references(:conversation_sessions,
          column: :id,
          name: "reasoning_outcomes_session_uuid_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :workspace_uuid,
        references(:workspaces,
          column: :id,
          name: "reasoning_outcomes_workspace_uuid_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:messages, "messages_session_id_fkey"))

    alter table(:messages) do
      modify(
        :session_id,
        references(:conversation_sessions,
          column: :id,
          name: "messages_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(
      unique_index(:messages, [:tenant_id, :session_id, :sequence],
        name: "messages_unique_session_sequence_index"
      )
    )

    drop_if_exists(
      unique_index(:messages, [:tenant_id, :session_id, :request_id, :tool_call_id, :role],
        name: "messages_unique_live_tool_row_index"
      )
    )

    drop_if_exists(
      unique_index(:messages, [:tenant_id, :session_id, :import_hash],
        name: "messages_unique_import_hash_index"
      )
    )

    create(
      unique_index(:messages, [:session_id, :sequence],
        name: "messages_unique_session_sequence_index"
      )
    )

    create(
      unique_index(:messages, [:session_id, :request_id, :tool_call_id, :role],
        name: "messages_unique_live_tool_row_index",
        where: "(request_id IS NOT NULL AND role IN ('tool_call', 'tool_result'))"
      )
    )

    create(
      unique_index(:messages, [:session_id, :import_hash],
        name: "messages_unique_import_hash_index",
        where: "(import_hash IS NOT NULL)"
      )
    )

    drop_if_exists(index(:messages, [:tenant_id, :session_id, :sequence]))

    drop_if_exists(index(:messages, [:tenant_id, :request_id]))

    drop_if_exists(index(:messages, [:tenant_id, :session_id, :role]))

    drop_if_exists(index(:messages, [:tenant_id, :tool_call_id]))

    drop_if_exists(index(:messages, [:tenant_id, :parent_message_id]))

    drop_if_exists(index(:messages, [:tenant_id, :session_id]))

    drop_if_exists(
      index(:messages, [:tenant_id, :request_id, :role], name: "messages_request_id_role_idx")
    )

    create(index(:messages, [:session_id, :sequence]))

    create(index(:messages, [:request_id]))

    create(index(:messages, [:session_id, :role]))

    create(index(:messages, [:tool_call_id], where: "tool_call_id IS NOT NULL"))

    create(index(:messages, [:parent_message_id], where: "parent_message_id IS NOT NULL"))

    create(index(:messages, [:tenant_id, :session_id]))

    create(
      index(:messages, [:request_id, :role],
        name: "messages_request_id_role_idx",
        where: "request_id IS NOT NULL"
      )
    )
  end
end
