defmodule JidoClaw.Repo.Migrations.CronFireFencing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cron_jobs) do
      add :failure_count, :bigint, null: false, default: 0
      add :last_fire_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:cron_jobs) do
      remove :last_fire_at
      remove :failure_count
    end
  end
end
