defmodule JidoClaw.Repo.Migrations.AddTraceEventSchemaVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trace_events) do
      add :schema_version, :bigint, default: 1
    end
  end

  def down do
    alter table(:trace_events) do
      remove :schema_version
    end
  end
end
