defmodule JidoClaw.Repo.Migrations.DropFolioTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:folio_actions)

    drop table(:folio_inbox_items)

    drop table(:folio_projects)
  end

  def down do
    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
