defmodule JidoClaw.Repo.Migrations.AddTraceDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trace_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :text
      add :trace_id, :text, null: false
      add :seq, :bigint, null: false
      add :at_ms, :bigint, null: false
      add :source, :text, null: false
      add :category, :text, null: false
      add :event, :text, null: false
      add :phase, :text
      add :name, :text
      add :status, :text
      add :duration_ms, :bigint
      add :request_id, :text
      add :run_id, :text
      add :span_id, :text
      add :parent_span_id, :text
      add :measurements, :map, default: %{}
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:trace_events, [:tenant_id, :run_id], where: "run_id IS NOT NULL")

    create index(:trace_events, [:tenant_id, :request_id], where: "request_id IS NOT NULL")

    create index(:trace_events, [:tenant_id, :trace_id, :seq])

    create unique_index(:trace_events, [:trace_id, :seq],
             name: "trace_events_unique_trace_seq_index"
           )

    create table(:trace_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :trace_id, :text, null: false
      add :tenant_id, :text
      add :request_id, :text
      add :run_id, :text
      add :agent_id, :text
      add :status, :text
      add :started_at_ms, :bigint
      add :completed_at_ms, :bigint
      add :summary, :map, default: %{}
      add :last_seq, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:trace_runs, [:tenant_id, :inserted_at])

    create index(:trace_runs, [:tenant_id, :agent_id], where: "agent_id IS NOT NULL")

    create index(:trace_runs, [:tenant_id, :run_id], where: "run_id IS NOT NULL")

    create index(:trace_runs, [:tenant_id, :request_id], where: "request_id IS NOT NULL")

    create unique_index(:trace_runs, [:trace_id], name: "trace_runs_unique_trace_id_index")
  end

  def down do
    drop_if_exists unique_index(:trace_runs, [:trace_id],
                     name: "trace_runs_unique_trace_id_index"
                   )

    drop_if_exists index(:trace_runs, [:tenant_id, :request_id])

    drop_if_exists index(:trace_runs, [:tenant_id, :run_id])

    drop_if_exists index(:trace_runs, [:tenant_id, :agent_id])

    drop_if_exists index(:trace_runs, [:tenant_id, :inserted_at])

    drop table(:trace_runs)

    drop_if_exists unique_index(:trace_events, [:trace_id, :seq],
                     name: "trace_events_unique_trace_seq_index"
                   )

    drop_if_exists index(:trace_events, [:tenant_id, :trace_id, :seq])

    drop_if_exists index(:trace_events, [:tenant_id, :request_id])

    drop_if_exists index(:trace_events, [:tenant_id, :run_id])

    drop table(:trace_events)
  end
end
