defmodule JidoClaw.Repo.Migrations.AddWorkflowStepDeadline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_steps) do
      add :deadline, :map
    end
  end

  def down do
    alter table(:workflow_steps) do
      remove :deadline
    end
  end
end
