defmodule JidoClaw.Repo.Migrations.V060CreateWorkspacesAndSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:path, :text, null: false)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "workspaces_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "workspaces_project_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:tenant_id, :text, null: false)
      add(:embedding_policy, :text, null: false, default: "disabled")
      add(:consolidation_policy, :text, null: false, default: "disabled")
      add(:metadata, :map, default: %{})
      add(:archived_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:workspaces, [:tenant_id, :user_id, :path]))

    create(
      unique_index(:workspaces, [:tenant_id, :user_id, :path],
        name: "workspaces_unique_user_path_authed_index",
        where: "(user_id IS NOT NULL)"
      )
    )

    create(
      unique_index(:workspaces, [:tenant_id, :path],
        name: "workspaces_unique_user_path_cli_index",
        where: "(user_id IS NULL)"
      )
    )

    create table(:conversation_sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "conversation_sessions_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "conversation_sessions_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:kind, :text, null: false)
      add(:external_id, :text, null: false)
      add(:tenant_id, :text, null: false)
      add(:started_at, :utc_datetime_usec, null: false)
      add(:last_active_at, :utc_datetime_usec, null: false)
      add(:closed_at, :utc_datetime_usec)
      add(:idle_timeout_seconds, :bigint, default: 300)
      add(:next_sequence, :bigint, default: 1)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:conversation_sessions, [:tenant_id, :last_active_at]))

    create(index(:conversation_sessions, [:workspace_id, :started_at]))

    create(
      unique_index(:conversation_sessions, [:tenant_id, :workspace_id, :kind, :external_id],
        name: "conversation_sessions_unique_external_index"
      )
    )
  end

  def down do
    drop(constraint(:conversation_sessions, "conversation_sessions_workspace_id_fkey"))

    drop(constraint(:conversation_sessions, "conversation_sessions_user_id_fkey"))

    drop_if_exists(
      unique_index(:conversation_sessions, [:tenant_id, :workspace_id, :kind, :external_id],
        name: "conversation_sessions_unique_external_index"
      )
    )

    drop_if_exists(index(:conversation_sessions, [:workspace_id, :started_at]))

    drop_if_exists(index(:conversation_sessions, [:tenant_id, :last_active_at]))

    drop(table(:conversation_sessions))

    drop(constraint(:workspaces, "workspaces_user_id_fkey"))

    drop(constraint(:workspaces, "workspaces_project_id_fkey"))

    drop_if_exists(
      unique_index(:workspaces, [:tenant_id, :path],
        name: "workspaces_unique_user_path_cli_index"
      )
    )

    drop_if_exists(
      unique_index(:workspaces, [:tenant_id, :user_id, :path],
        name: "workspaces_unique_user_path_authed_index"
      )
    )

    drop_if_exists(index(:workspaces, [:tenant_id, :user_id, :path]))

    drop(table(:workspaces))
  end
end
