defmodule JidoClaw.Cron.Job do
  @moduledoc """
  Persistent cron-job definition row.

  Replaces the legacy `.jido/cron.yaml` file-store. Identity is the
  composite `(tenant_id, job_id)` — `job_id` is user-supplied or
  generated by `Tools.ScheduleTask`'s id helper.

  `disabled_at` is set when the cron worker auto-disables a job
  after 3 consecutive failures. The `:for_tenant` read action
  filters to `is_nil(disabled_at)` so a restart re-loads only
  active rows; `:enable` clears the timestamp.

  `mode: :system_job` rows are config-driven in v0.6.4 and don't
  flow through this resource yet — kept on the schema for forward
  compatibility.

  `target` (`:agent | :workflow | :mfa`) is the execution-target
  dimension, orthogonal to `mode`. Dispatch is legacy-first:
  `Cron.Dispatcher` routes `mode: :system_job` to MFA *before*
  consulting `target`, so every pre-`target` row keeps working and
  new rows default to `target: :agent`. `:workflow` rows carry a
  `workflow_name` (a skill) and drive a tracked
  `JidoClaw.Orchestration.WorkflowRun`. `run_count`/`last_run_at`
  are system-managed durability counters stamped by `:record_run`.

  `timezone` (IANA name, default `"Etc/UTC"`) is the wall-clock zone a
  `:cron` expression is read in — `"0 9 * * *"` with `"America/New_York"`
  fires at 09:00 local. It is inert for `:every` / `:at` schedules.
  """

  use JidoClaw.Resource, domain: JidoClaw.Cron

  @modes [:main, :isolated, :system_job]
  @targets [:agent, :workflow, :mfa]
  @schedule_kinds [:cron, :every, :at]

  postgres do
    table("cron_jobs")
    repo(JidoClaw.Repo)

    custom_indexes do
      index([:tenant_id, :disabled_at])
    end
  end

  multitenancy do
    strategy(:attribute)
    attribute(:tenant_id)
    global?(false)
  end

  code_interface do
    define(:upsert, action: :upsert)
    define(:by_id, action: :by_id, args: [:id], get?: true)
    define(:by_job_id, action: :by_job_id, args: [:job_id], get?: true)
    define(:by_id_global, action: :by_id_global, args: [:id], get?: true)
    define(:remove, action: :remove)
    define(:disable, action: :disable)
    define(:enable, action: :enable)
    define(:record_run, action: :record_run)
    define(:for_tenant, action: :for_tenant)
  end

  actions do
    defaults([:read, :destroy])

    create :upsert do
      primary?(true)
      upsert?(true)
      upsert_identity(:unique_job)

      upsert_fields([
        :task,
        :mode,
        :target,
        :workflow_name,
        :workflow_input,
        :schedule_kind,
        :schedule_value,
        :timezone,
        :mfa_module,
        :mfa_function,
        :mfa_args,
        :metadata,
        :updated_at
      ])

      accept([
        :job_id,
        :task,
        :mode,
        :target,
        :workflow_name,
        :workflow_input,
        :schedule_kind,
        :schedule_value,
        :timezone,
        :mfa_module,
        :mfa_function,
        :mfa_args,
        :metadata
      ])

      # Defense in depth: a bad row can't silently always-fail at dispatch.
      # `where:` ANDs its conditions, so the MFA requirement is two separate
      # statements (target == :mfa OR mode == :system_job) to get OR semantics.
      validate(present(:workflow_name), where: [attribute_equals(:target, :workflow)])
      validate(present([:mfa_module, :mfa_function]), where: [attribute_equals(:target, :mfa)])

      validate(present([:mfa_module, :mfa_function]),
        where: [attribute_equals(:mode, :system_job)]
      )
    end

    update :disable do
      accept([])
      change(set_attribute(:disabled_at, &DateTime.utc_now/0))
    end

    update :enable do
      accept([])
      change(set_attribute(:disabled_at, nil))
    end

    # Durability counters, stamped best-effort by Cron.Worker after each
    # tick. Both changes are atomic (single-writer per job), so no
    # `require_atomic? false` and no record load inside the action.
    update :record_run do
      accept([])
      change(atomic_update(:run_count, expr(run_count + 1)))
      change(atomic_update(:last_run_at, expr(now())))
    end

    destroy :remove do
    end

    read :by_id do
      get?(true)
      argument(:id, :uuid, allow_nil?: false)
      filter(expr(id == ^arg(:id)))
    end

    read :by_id_global do
      get?(true)
      multitenancy(:bypass)
      argument(:id, :uuid, allow_nil?: false)
      filter(expr(id == ^arg(:id)))
    end

    read :by_job_id do
      get?(true)
      argument(:job_id, :string, allow_nil?: false)
      filter(expr(job_id == ^arg(:job_id)))
    end

    read :for_tenant do
      filter(expr(is_nil(disabled_at)))
      prepare(build(sort: [inserted_at: :asc]))
    end
  end

  attributes do
    uuid_primary_key(:id)

    attribute :tenant_id, :string do
      allow_nil?(false)
      public?(true)
    end

    attribute :job_id, :string do
      allow_nil?(false)
      public?(true)
    end

    attribute :task, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :mode, :atom do
      allow_nil?(false)
      public?(true)
      default(:main)
      constraints(one_of: @modes)
    end

    attribute :target, :atom do
      allow_nil?(false)
      public?(true)
      default(:agent)
      constraints(one_of: @targets)
    end

    attribute :workflow_name, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :workflow_input, :map do
      allow_nil?(true)
      public?(true)
      default(%{})
    end

    attribute :schedule_kind, :atom do
      allow_nil?(false)
      public?(true)
      constraints(one_of: @schedule_kinds)
    end

    attribute :schedule_value, :string do
      allow_nil?(false)
      public?(true)
    end

    # IANA wall-clock zone for interpreting :cron expressions. Only the :cron
    # kind reads it (`JidoClaw.Cron.NextRun`); :every / :at are tz-inert.
    # Default "Etc/UTC" keeps pre-timezone rows firing exactly as before.
    attribute :timezone, :string do
      allow_nil?(false)
      public?(true)
      default("Etc/UTC")
    end

    attribute :mfa_module, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :mfa_function, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :mfa_args, :map do
      allow_nil?(true)
      public?(true)
      default(%{})
    end

    attribute :disabled_at, :utc_datetime_usec do
      allow_nil?(true)
      public?(true)
    end

    attribute :run_count, :integer do
      allow_nil?(false)
      public?(true)
      default(0)
    end

    attribute :last_run_at, :utc_datetime_usec do
      allow_nil?(true)
      public?(true)
    end

    attribute :metadata, :map do
      allow_nil?(false)
      public?(true)
      default(%{})
    end

    timestamps()
  end

  relationships do
    belongs_to :tenant, JidoClaw.Tenants.Tenant do
      define_attribute?(false)
      attribute_writable?(true)
      allow_nil?(false)
    end
  end

  identities do
    identity(:unique_job, [:tenant_id, :job_id])
  end
end
