defmodule JidoClaw.Cron.Job do
  @moduledoc """
  Persistent cron-job definition row.

  Replaces the legacy `.jido/cron.yaml` file-store. Identity is the
  composite `(tenant_id, job_id)` — `job_id` is user-supplied or
  generated by `Tools.ScheduleTask`'s id helper.

  `disabled_at` is set when the cron worker auto-disables a job
  after 3 consecutive failures. The `:for_tenant` read action
  filters to `is_nil(disabled_at)` so a restart re-loads only
  active rows; `:enable` clears the timestamp.

  `mode: :system_job` rows are config-driven in v0.6.4 and don't
  flow through this resource yet — kept on the schema for forward
  compatibility.
  """

  use JidoClaw.Resource, domain: JidoClaw.Cron

  @modes [:main, :isolated, :system_job]
  @schedule_kinds [:cron, :every, :at]

  postgres do
    table("cron_jobs")
    repo(JidoClaw.Repo)

    custom_indexes do
      index([:tenant_id, :disabled_at])
    end
  end

  multitenancy do
    strategy(:attribute)
    attribute(:tenant_id)
    global?(false)
  end

  code_interface do
    define(:upsert, action: :upsert)
    define(:by_id, action: :by_id, args: [:id], get?: true)
    define(:by_job_id, action: :by_job_id, args: [:job_id], get?: true)
    define(:by_id_global, action: :by_id_global, args: [:id], get?: true)
    define(:remove, action: :remove)
    define(:disable, action: :disable)
    define(:enable, action: :enable)
    define(:for_tenant, action: :for_tenant)
  end

  actions do
    defaults([:read, :destroy])

    create :upsert do
      primary?(true)
      upsert?(true)
      upsert_identity(:unique_job)

      upsert_fields([
        :task,
        :mode,
        :schedule_kind,
        :schedule_value,
        :mfa_module,
        :mfa_function,
        :mfa_args,
        :metadata,
        :updated_at
      ])

      accept([
        :job_id,
        :task,
        :mode,
        :schedule_kind,
        :schedule_value,
        :mfa_module,
        :mfa_function,
        :mfa_args,
        :metadata
      ])
    end

    update :disable do
      accept([])
      change(set_attribute(:disabled_at, &DateTime.utc_now/0))
    end

    update :enable do
      accept([])
      change(set_attribute(:disabled_at, nil))
    end

    destroy :remove do
    end

    read :by_id do
      get?(true)
      argument(:id, :uuid, allow_nil?: false)
      filter(expr(id == ^arg(:id)))
    end

    read :by_id_global do
      get?(true)
      multitenancy(:bypass)
      argument(:id, :uuid, allow_nil?: false)
      filter(expr(id == ^arg(:id)))
    end

    read :by_job_id do
      get?(true)
      argument(:job_id, :string, allow_nil?: false)
      filter(expr(job_id == ^arg(:job_id)))
    end

    read :for_tenant do
      filter(expr(is_nil(disabled_at)))
      prepare(build(sort: [inserted_at: :asc]))
    end
  end

  attributes do
    uuid_primary_key(:id)

    attribute :tenant_id, :string do
      allow_nil?(false)
      public?(true)
    end

    attribute :job_id, :string do
      allow_nil?(false)
      public?(true)
    end

    attribute :task, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :mode, :atom do
      allow_nil?(false)
      public?(true)
      default(:main)
      constraints(one_of: @modes)
    end

    attribute :schedule_kind, :atom do
      allow_nil?(false)
      public?(true)
      constraints(one_of: @schedule_kinds)
    end

    attribute :schedule_value, :string do
      allow_nil?(false)
      public?(true)
    end

    attribute :mfa_module, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :mfa_function, :string do
      allow_nil?(true)
      public?(true)
    end

    attribute :mfa_args, :map do
      allow_nil?(true)
      public?(true)
      default(%{})
    end

    attribute :disabled_at, :utc_datetime_usec do
      allow_nil?(true)
      public?(true)
    end

    attribute :metadata, :map do
      allow_nil?(false)
      public?(true)
      default(%{})
    end

    timestamps()
  end

  relationships do
    belongs_to :tenant, JidoClaw.Tenants.Tenant do
      define_attribute?(false)
      attribute_writable?(true)
    end
  end

  identities do
    identity(:unique_job, [:tenant_id, :job_id])
  end
end
